// YouTube videos shown on the site (French voice-over). Posters are self-hosted under
// public/media/video/ so that nothing is requested from YouTube before the visitor clicks.
// The data lives in videos-data.ts, generated by video-studio/site_sync.py as each video is published.
import { COMPARISON_VIDEO_DATA, GUIDE_VIDEO_DATA, PRESENTATION_VIDEO_ID, SERVICE_VIDEO_DATA } from "./videos-data";

export type SiteVideo = { id: string; poster: string };

// Key: `${audience}/${slug}` of the service (src/lib/services/catalog.ts).
export const SERVICE_VIDEOS: Record<string, SiteVideo> = SERVICE_VIDEO_DATA;

// Key: guide article slug (src/lib/guide/articles.ts).
export const GUIDE_VIDEOS: Record<string, SiteVideo> = GUIDE_VIDEO_DATA;

export const PRESENTATION_VIDEO: SiteVideo = { id: PRESENTATION_VIDEO_ID, poster: "/media/video/presentation-poster.webp" };

// « Avocat ou service juridique externalisé » — shown on /alternative-embauche-juriste.
export const COMPARISON_VIDEO: SiteVideo | null = COMPARISON_VIDEO_DATA;

export const VIDEO_STRINGS = {
  fr: { heading: "La prestation en vidéo", play: "Lire la vidéo", note: "" },
  de: { heading: "Die Leistung im Video", play: "Video abspielen", note: "Video auf Französisch." },
  en: { heading: "This service on video", play: "Play the video", note: "Video in French." },
  it: { heading: "La prestazione in video", play: "Guarda il video", note: "Video in francese." },
} as const;
