import type { CategoryId } from "@/lib/services/catalog";
import type { CategoryText, ServiceText } from "./types";

const categories: Record<CategoryId, CategoryText> = {
  travail: { name: "Arbeit", lead: "Ihre Rechte gegenüber dem Arbeitgeber" },
  logement: { name: "Wohnen & Nachbarschaft", lead: "Miete, Mängel, Kaution, Kündigung" },
  consommation: { name: "Einkäufe, Verträge & Reisen", lead: "Garantie, Kündigung, Rückerstattung" },
  argent: { name: "Geld & Betreibungen", lead: "Geld zurückholen, Betreibung bestreiten" },
  administration: { name: "Steuern & Sozialversicherungen", lead: "Entscheide innert 30 Tagen anfechten" },
  famille: { name: "Familie & Vorsorge", lead: "Ihre Angehörigen und Ihren Willen schützen" },
  "sur-mesure": { name: "Massgeschneidert", lead: "Ihre Situation ist nicht in der Liste" },
  recouvrement: { name: "Inkasso & Streitfälle", lead: "Kunden zum Zahlen bringen, Ihre Position verteidigen" },
  contrats: { name: "Verträge & AGB", lead: "Verträge, die Sie wirklich schützen" },
  employeurs: { name: "Arbeitgeber", lead: "Einstellen, führen und sich sicher trennen" },
  conformite: { name: "Compliance & Gesellschaft", lead: "DSG, Geschäftsmiete, Gesellschafter" },
};

const services: Record<string, ServiceText> = {
  "analyse-certificat-de-travail": {
    name: "Analyse des Arbeitszeugnisses",
    short: "Jede Formulierung Ihres Zeugnisses entschlüsselt: was Ihnen nützt, was Ihnen schadet, was fehlt.",
    intro: "Ein Arbeitszeugnis kann positiv wirken und trotzdem Codes, Lücken oder Nuancen enthalten, die Ihre Bewerbungen bremsen. Wir analysieren es Satz für Satz und sagen Ihnen, was es Personalverantwortlichen wirklich sagt.",
    included: [
      "Prüfung jedes Satzes, inklusive Codes und Auslassungen",
      "Gesamtbewertung: sehr gut, gut, mittel oder zu korrigieren",
      "Liste der Punkte, deren Änderung Sie verlangen können",
      "Klare Empfehlung: behalten oder Berichtigung verlangen",
    ],
    needs: "Ihr Arbeitszeugnis (lesbares Foto oder PDF) und wenn möglich Ihr Stellenbeschrieb.",
    note: "Ihr Arbeitgeber muss Ihnen ein vollständiges, wahres und wohlwollend formuliertes Zeugnis über Art und Dauer des Arbeitsverhältnisses, Leistung und Verhalten ausstellen (Art. 330a OR). Ein Zwischenzeugnis können Sie jederzeit verlangen.",
    faq: [
      { q: "Was ist eine codierte Formulierung?", a: "Ein scheinbar positiver Satz, der eine Schwäche signalisiert, etwa eine Zufriedenheit «im Grossen und Ganzen». Die Analyse erkennt und erklärt solche Formulierungen." },
      { q: "Und wenn das Zeugnis korrigiert werden muss?", a: "Dann können Sie die Berichtigung bestellen: Der Preis der Analyse wird angerechnet, wenn Sie innert 30 Tagen bestellen." },
    ],
  },
  "rectification-certificat-de-travail": {
    name: "Arbeitszeugnis: Berichtigung verlangen",
    short: "Analyse Ihres Zeugnisses und Brief an den Arbeitgeber mit den Umformulierungen, die Sie verlangen können.",
    intro: "Ihr Zeugnis enthält vage Formulierungen, Lücken oder Sätze, die Ihnen schaden? Wir analysieren es Satz für Satz und verfassen den Brief an Ihren Arbeitgeber mit den Umformulierungen, auf die Sie Anspruch haben.",
    included: [
      "Vollständige Analyse des Zeugnisses, inklusive Codes und Lücken",
      "Vorschlag für einen korrigierten Text, Satz für Satz",
      "Berichtigungsbegehren, versandbereit",
      "Vorgehen, falls der Arbeitgeber ablehnt",
    ],
    needs: "Ihr Arbeitszeugnis, Ihr Arbeitsvertrag, falls vorhanden, und zwei Zeilen dazu, was Sie stört.",
    note: "Das Zeugnis muss vollständig, wahr und wohlwollend sein (Art. 330a OR). Bei Ablehnung ist eine Berichtigungsklage möglich: Bei arbeitsrechtlichen Streitigkeiten bis CHF 30'000 ist das Verfahren kostenlos (Art. 114 ZPO).",
    faq: [
      { q: "Erfährt mein Arbeitgeber, dass Sie mir helfen?", a: "Nein. Der Brief wird in Ihrem Namen verfasst und Sie versenden ihn selbst." },
      { q: "Kann mein Arbeitgeber ablehnen?", a: "Eine unrichtige oder unvollständige Angabe muss er korrigieren. Lehnt er grundlos ab, bereitet der Brief die nächsten Schritte vor, und wir erklären Ihnen die Möglichkeiten." },
    ],
  },
  "licenciement-opposition": {
    name: "Kündigung: Prüfung und Einsprache",
    short: "Fristen, Sperrfristen, Missbrauch: Wir prüfen Ihre Kündigung und verfassen die Einsprache.",
    intro: "Sie wurden gerade entlassen und etwas scheint nicht richtig? Wir prüfen, ob die Kündigung die Fristen einhält, in eine Sperrfrist fällt oder missbräuchlich sein könnte, und verfassen Ihre schriftliche Einsprache.",
    included: [
      "Prüfung der Kündigungsfrist und des Enddatums",
      "Kontrolle der Sperrfristen: Krankheit, Unfall, Schwangerschaft, Militärdienst",
      "Analyse des Grundes: missbräuchlich oder nicht",
      "Einsprache und Verlangen einer schriftlichen Begründung, versandbereit",
    ],
    needs: "Das Kündigungsschreiben, Ihren Arbeitsvertrag und die wichtigen Daten (Arbeitsunfähigkeit, Gespräche …).",
    note: "Um eine Entschädigung wegen missbräuchlicher Kündigung zu verlangen, müssen Sie vor Ende der Kündigungsfrist schriftlich Einsprache erheben und innert 180 Tagen nach Vertragsende klagen (Art. 336b OR). Eine Kündigung während einer Sperrfrist ist nichtig (Art. 336c OR).",
    faq: [
      { q: "Wie viel Zeit habe ich?", a: "Die Einsprache muss vor Ende der Kündigungsfrist beim Arbeitgeber eintreffen. Wählen Sie die Express-Option, wenn das Datum naht." },
      { q: "Bekomme ich meine Stelle zurück?", a: "Nach Schweizer Recht bleibt eine missbräuchliche Kündigung gültig; sie gibt Anspruch auf höchstens sechs Monatslöhne Entschädigung. Eine Kündigung während einer Sperrfrist ist hingegen nichtig." },
    ],
  },
  "relecture-contrat-de-travail": {
    name: "Prüfung des Arbeitsvertrags",
    short: "Vor der Unterschrift: Probezeit, Überstunden, Konkurrenzverbot, Ferien, alles geprüft.",
    intro: "Ihnen wird ein Vertrag vorgelegt und Sie wollen wissen, was Sie unterschreiben? Wir prüfen ihn und zeigen Ihnen ungünstige, ungewöhnliche oder nichtige Klauseln sowie Verhandlungsspielraum.",
    included: [
      "Vollständige Prüfung des Vertrags (bis 15 Seiten)",
      "Risikopunkte: Probezeit, Überstunden, Konkurrenzverbot, Mobilität, Ferien",
      "Abgleich mit dem anwendbaren Gesamtarbeitsvertrag, falls vorhanden",
      "Änderungsvorschläge für die Verhandlung",
    ],
    needs: "Den angebotenen Vertrag und, falls vorhanden, das Stelleninserat oder Angebot.",
    note: "Die Probezeit darf höchstens drei Monate dauern (Art. 335b OR). Ein Konkurrenzverbot gilt nur schriftlich und wenn Sie Einblick in Kundenkreis oder Geschäftsgeheimnisse haben (Art. 340 OR).",
    faq: [
      { q: "Kann ich meinen Vertrag verhandeln?", a: "Ja, vor der Unterschrift. Wir nennen Ihnen die wichtigsten Punkte und eine höfliche Formulierung dafür." },
      { q: "Und wenn ich schon unterschrieben habe?", a: "Die Prüfung lohnt sich trotzdem: Gewisse Klauseln sind auch unterschrieben nichtig. Wir sagen Ihnen, welche." },
    ],
  },
  "salaire-impaye": {
    name: "Unbezahlter Lohn, Überstunden oder Ferien",
    short: "Berechnung Ihrer Ansprüche und Mahnung an den Arbeitgeber mit Zahlungsfrist.",
    intro: "Verspäteter Lohn, nie bezahlte Überstunden, ignorierter Feriensaldo bei Vertragsende: Wir berechnen genau, was Ihnen zusteht, und verfassen die Mahnung an Ihren Arbeitgeber.",
    included: [
      "Detaillierte Berechnung (Lohn, Stunden, Ferien, 13. Monatslohn)",
      "Prüfung von Vertrag und Gesamtarbeitsvertrag",
      "Mahnung mit Zahlungsfrist, versandbereit",
      "Vorgehen, falls der Arbeitgeber nicht zahlt",
    ],
    needs: "Ihren Vertrag, Ihre Lohnabrechnungen und, falls vorhanden, eine Aufstellung Ihrer Stunden.",
    note: "Überstunden werden mit einem Zuschlag von 25 % bezahlt, sofern nichts anderes schriftlich vereinbart ist (Art. 321c OR). Lohnforderungen verjähren nach fünf Jahren (Art. 128 OR).",
    faq: [
      { q: "Kann ich fordern, während ich noch dort arbeite?", a: "Ja. Der Brief ist bestimmt, aber korrekt formuliert, um die Beziehung zu schonen." },
      { q: "Und wenn der Arbeitgeber nicht reagiert?", a: "Sie können die Schlichtungsbehörde anrufen. Wir verfassen das Gesuch: Leistung «Schlichtungsgesuch (Arbeit)»." },
    ],
  },
  "lettre-de-demission": {
    name: "Kündigungsschreiben",
    short: "Die richtige Frist, das richtige Enddatum, der Feriensaldo und das Arbeitszeugnis.",
    intro: "Eine falsch datierte Kündigung kann Sie einen Monatslohn kosten. Wir berechnen Ihre Frist und verfassen einen klaren Brief, der auch Ferien und Arbeitszeugnis regelt.",
    included: [
      "Berechnung der Kündigungsfrist und des genauen Enddatums",
      "Persönliches Kündigungsschreiben",
      "Verlangen des Arbeitszeugnisses und Hinweis zum Feriensaldo",
    ],
    needs: "Ihren Arbeitsvertrag und das gewünschte Austrittsdatum.",
    note: "Ohne andere Abrede beträgt die Frist im ersten Dienstjahr einen Monat, vom zweiten bis neunten zwei Monate, danach drei Monate, jeweils auf Monatsende (Art. 335c OR). Der Brief muss vor Fristbeginn beim Arbeitgeber eintreffen.",
    faq: [
      { q: "Kann ich früher gehen?", a: "Nur mit Zustimmung des Arbeitgebers. Der Brief kann ein früheres Datum vorschlagen und trotzdem die gesetzliche Frist wahren." },
      { q: "Muss ich eingeschrieben senden?", a: "Empfehlenswert, um den Empfang zu beweisen, oder persönlich gegen Unterschrift übergeben." },
    ],
  },
  "requete-conciliation-travail": {
    name: "Schlichtungsgesuch (Arbeit)",
    short: "Ihr Gesuch, bereit zur Einreichung bei der Schlichtungsbehörde, mit geordneten Beilagen.",
    intro: "Ihr Arbeitgeber zahlt trotz Ihrer Briefe nicht? Das Verfahren vor dem Arbeitsgericht beginnt grundsätzlich mit einem Schlichtungsversuch. Wir verfassen Ihr Gesuch und erklären Ihnen den Ablauf der Verhandlung.",
    included: [
      "Schlichtungsgesuch mit bezifferten Rechtsbegehren",
      "Liste und Ordnung der Beilagen",
      "Vorbereitungsblatt für die Schlichtungsverhandlung",
    ],
    needs: "Ihren Vertrag, die Korrespondenz mit dem Arbeitgeber und Belege für Ihre Ansprüche.",
    note: "Bei arbeitsrechtlichen Streitigkeiten bis CHF 30'000 gilt das vereinfachte, kostenlose Verfahren (Art. 114 und 243 ZPO). Sie reichen das Gesuch selbst ein: Thrax Legal vertritt Sie nicht vor Behörden.",
    faq: [
      { q: "Muss ich zur Verhandlung?", a: "Ja, das persönliche Erscheinen ist grundsätzlich Pflicht. Das Vorbereitungsblatt hilft Ihnen, Ihre Position ruhig darzulegen." },
      { q: "Und wenn mein Fall komplex ist?", a: "Braucht es einen Anwalt, sagen wir es Ihnen, bevor Sie bezahlen." },
    ],
  },
  "baisse-de-loyer": {
    name: "Mietzinssenkung verlangen",
    short: "Berechnung der Senkung, auf die Sie Anspruch haben, und versandbereiter Brief an den Vermieter.",
    intro: "Sinkt der hypothekarische Referenzzinssatz, kann auch Ihre Miete sinken. Wir prüfen Ihren Anspruch, berechnen die mögliche Senkung und verfassen den Brief an Vermieter oder Verwaltung.",
    included: [
      "Prüfung des Referenzzinssatzes und der letzten Mietzinsanpassung",
      "Berechnung der möglichen Senkung",
      "Herabsetzungsbegehren, versandbereit",
      "Vorgehen bei Ablehnung",
    ],
    needs: "Ihren Mietvertrag und die letzte Mietzinsmitteilung.",
    note: "Das Begehren erfolgt schriftlich auf den nächsten Kündigungstermin. Der Vermieter hat 30 Tage Zeit; lehnt er ab oder schweigt er, können Sie innert 30 Tagen die Schlichtungsbehörde anrufen (Art. 270a OR).",
    faq: [
      { q: "Darf mir der Vermieter deswegen kündigen?", a: "Nein. Eine Kündigung, weil der Mieter seine Rechte geltend macht, ist anfechtbar (Art. 271a OR)." },
      { q: "Wie viel kann ich sparen?", a: "Das hängt von der letzten Anpassung ab. Die Berechnung zeigt den genauen Betrag, bevor Sie etwas senden." },
    ],
  },
  "contestation-loyer-initial": {
    name: "Anfechtung des Anfangsmietzinses",
    short: "Missbräuchliche Anfangsmiete? Sie haben 30 Tage: Analyse und einreichebereites Gesuch.",
    intro: "Sie sind eben eingezogen und die Miete ist deutlich höher als beim Vormieter? Vielleicht können Sie sie anfechten. Wir prüfen Ihre Chancen und verfassen das Gesuch an die Schlichtungsbehörde.",
    included: [
      "Prüfung der Anfechtungsvoraussetzungen",
      "Kontrolle des amtlichen Formulars",
      "Gesuch an die Schlichtungsbehörde, einreichebereit",
      "Erläuterung des Verfahrens und der Risiken",
    ],
    needs: "Ihren Mietvertrag, das amtliche Formular (falls erhalten) und das Datum der Schlüsselübergabe.",
    note: "Die Frist beträgt 30 Tage ab Übernahme der Sache (Art. 270 OR). In mehreren Kantonen muss der Vermieter den Vormietzins auf einem amtlichen Formular mitteilen; fehlt es, kann auch dies geltend gemacht werden.",
    faq: [
      { q: "Ich bin ausserhalb der Frist, was nun?", a: "Fehlte das amtliche Formular, gibt es andere Möglichkeiten. Bestellen Sie ein Rechtsgespräch zur Abklärung." },
      { q: "Gefährdet das meinen Mietvertrag?", a: "Während des Verfahrens und drei Jahre danach darf der Vermieter deswegen nicht kündigen (Art. 271a OR)." },
    ],
  },
  "defaut-logement": {
    name: "Mangel in der Wohnung: Mietzinsreduktion",
    short: "Schimmel, Defekt, Lärm, Bauarbeiten: Mängelrüge und Herabsetzungsbegehren.",
    intro: "Schimmel, defekte Heizung, Wasserschaden, lärmige Baustelle: Ein andauernder Mangel gibt Anspruch auf Behebung und Mietzinsreduktion. Wir verfassen Mängelrüge und Reduktionsbegehren formgerecht.",
    included: [
      "Einordnung des Mangels und übliche Reduktion",
      "Mängelrüge mit Frist zur Behebung",
      "Herabsetzungsbegehren",
      "Erklärung der Hinterlegung des Mietzinses, falls nötig",
    ],
    needs: "Fotos des Mangels, Datum der Entdeckung und Korrespondenz mit der Verwaltung.",
    note: "Hören Sie nie einfach auf, die Miete zu bezahlen: Das ist ein Kündigungsgrund. Die Hinterlegung ist erst nach schriftlicher Aufforderung und angemessener Frist möglich (Art. 259g OR). Die Reduktion gilt ab Kenntnis des Vermieters (Art. 259d OR).",
    faq: [
      { q: "Um wie viel kann die Miete sinken?", a: "Je nach Schwere und Dauer. Wir nennen Ihnen eine Bandbreite gemäss Praxis." },
      { q: "Und wenn die Verwaltung nicht reagiert?", a: "Der Brief setzt eine Frist. Danach können Sie hinterlegen oder die Schlichtungsbehörde anrufen." },
    ],
  },
  "garantie-de-loyer": {
    name: "Mietkaution zurückholen",
    short: "Bestrittene Instandstellungskosten, blockierte Kaution: Wir verfassen Ihre Reklamation.",
    intro: "Die frühere Verwaltung blockiert die Kaution oder verrechnet Instandstellungskosten? Wir prüfen, was wirklich verlangt werden darf, und verfassen Bestreitung und Freigabegesuch.",
    included: [
      "Analyse des Abnahmeprotokolls und der Kosten",
      "Abgrenzung normale Abnützung / Schäden zu Ihren Lasten",
      "Bestreitung und Gesuch um Freigabe der Kaution",
    ],
    needs: "Mietvertrag, Antritts- und Abnahmeprotokoll sowie die Abrechnung der Verwaltung.",
    note: "Normale Abnützung trägt der Vermieter (Art. 267 OR). Hat der Vermieter innert eines Jahres nach Mietende keinen Anspruch rechtlich geltend gemacht, können Sie die Bank um Freigabe ersuchen (Art. 257e OR).",
    faq: [
      { q: "Darf die Verwaltung die Kaution einfach behalten?", a: "Nicht unbegrenzt: Nach einem Jahr ohne Verfahren können Sie die Freigabe direkt bei der Bank verlangen." },
      { q: "Mir wird ein kompletter Anstrich verrechnet, ist das normal?", a: "Oft nicht: Die Lebensdauer des Anstrichs wird berücksichtigt. Der Brief bestreitet ungerechtfertigte Beträge." },
    ],
  },
  "resiliation-anticipee-bail": {
    name: "Vorzeitige Kündigung des Mietvertrags",
    short: "Vor Ablauf ausziehen, ohne Monatsmieten zu zahlen: Brief und Ersatzmieter.",
    intro: "Sie müssen vor dem Kündigungstermin ausziehen? Mit einem Ersatzmieter können Sie sich früher befreien. Wir verfassen das Kündigungsschreiben und die Vorstellung des Ersatzmieters.",
    included: [
      "Berechnung des ordentlichen Termins und der Fristen",
      "Korrekte vorzeitige Kündigung",
      "Vorstellungsschreiben für den Ersatzmieter",
    ],
    needs: "Ihren Mietvertrag und, falls schon vorhanden, die Angaben des Ersatzmieters.",
    note: "Der Ersatzmieter muss zahlungsfähig, dem Vermieter zumutbar und bereit sein, den Vertrag zu gleichen Bedingungen zu übernehmen (Art. 264 OR). Bei der Familienwohnung müssen beide Ehegatten unterzeichnen (Art. 266m OR).",
    faq: [
      { q: "Darf der Vermieter meinen Kandidaten ablehnen?", a: "Nur aus wichtigen Gründen. Sonst sind Sie auf das vorgeschlagene Datum befreit." },
      { q: "Wie viele Kandidaten braucht es?", a: "Einer genügt, wenn er die Voraussetzungen erfüllt. Zwei oder drei beschleunigen die Sache." },
    ],
  },
  "contestation-conge": {
    name: "Kündigung anfechten oder Erstreckung verlangen",
    short: "Sie haben 30 Tage: Gesuch an die Schlichtungsbehörde zur Aufhebung oder für mehr Zeit.",
    intro: "Sie haben die Kündigung erhalten? Sie können sie anfechten, wenn sie missbräuchlich ist, oder eine Erstreckung verlangen, wenn der Auszug Härten bringt. Wir verfassen das Gesuch an die Schlichtungsbehörde.",
    included: [
      "Prüfung der Formgültigkeit der Kündigung",
      "Analyse der Gründe: anfechtbar oder nicht",
      "Gesuch um Aufhebung und/oder Erstreckung, einreichebereit",
    ],
    needs: "Das amtliche Kündigungsformular, Umschlag oder Abholungsschein und Ihren Mietvertrag.",
    note: "Die Frist beträgt 30 Tage ab Empfang der Kündigung (Art. 273 OR). Eine Kündigung ohne amtliches Formular ist nichtig (Art. 266l und 266o OR). Die Erstreckung kann bei Wohnungen bis vier Jahre dauern (Art. 272b OR).",
    faq: [
      { q: "Ab wann läuft die Frist?", a: "Ab tatsächlichem Empfang oder letztem Tag der Abholfrist bei der Post. Wählen Sie Express, wenn das Datum naht." },
      { q: "Gewinne ich Zeit, auch wenn die Kündigung gültig ist?", a: "Oft ja: Eine Erstreckung ist bei Härtefällen möglich." },
    ],
  },
  "decompte-de-charges": {
    name: "Nebenkostenabrechnung anfechten",
    short: "Prüfung Ihrer Abrechnung Posten für Posten und Reklamation beim Vermieter.",
    intro: "Ihre Heiz- und Nebenkostenabrechnung ist explodiert? Wir prüfen jeden Posten und verfassen die Reklamation samt Gesuch um Einsicht in die Belege.",
    included: [
      "Abgleich der Posten mit dem Mietvertrag",
      "Erkennen nicht vereinbarter oder übermässiger Kosten",
      "Reklamation und Gesuch um Belegeinsicht",
    ],
    needs: "Ihren Mietvertrag und die bestrittene Abrechnung.",
    note: "Sie schulden nur Nebenkosten, die im Vertrag ausdrücklich vereinbart sind (Art. 257a OR), und dürfen die Belege einsehen (Art. 257b OR).",
    faq: [
      { q: "Muss ich den Saldo vorerst zahlen?", a: "Wir sagen Ihnen, welchen Teil Sie zahlen und welchen Sie bestreiten sollten." },
      { q: "Kann ich alte Abrechnungen anfechten?", a: "Oft ja, in gewissen Grenzen. Geben Sie die betroffenen Jahre an." },
    ],
  },
  "litige-de-voisinage": {
    name: "Nachbarschaftsstreit: formeller Brief",
    short: "Lärm, Pflanzen, Grenzen, Immissionen: ein klarer, rechtlich begründeter Brief.",
    intro: "Gespräche haben nichts gebracht und die Situation dauert an? Ein formeller, sachlicher und rechtlich begründeter Brief löst das Problem oft ohne Prozess. Wir verfassen ihn für Sie.",
    included: [
      "Analyse der Situation und der anwendbaren Regeln",
      "Formeller Brief an den Nachbarn oder die Verwaltung",
      "Tipps zur Beweissicherung",
    ],
    needs: "Eine Beschreibung des Problems, seine Dauer und, falls vorhanden, Fotos oder ein Lärmprotokoll.",
    note: "Jeder muss sich aller übermässigen Einwirkungen auf das Eigentum der Nachbarn enthalten (Art. 684 ZGB). Grenzabstände für Bäume und Pflanzen regelt das kantonale Recht.",
    faq: [
      { q: "Verschärft der Brief nicht die Lage?", a: "Er ist bestimmt, aber höflich formuliert, um eine Lösung zu ermöglichen." },
      { q: "Ich bin Mieter, an wen schreibe ich?", a: "Oft an die Verwaltung, die den ruhigen Gebrauch gewährleisten muss. Wir sagen Ihnen, an wen." },
    ],
  },
  "resiliation-de-contrat": {
    name: "Abo oder Vertrag kündigen",
    short: "Fitness, Telefon, Versicherung, Abo: die richtige Frist, Form und das richtige Datum.",
    intro: "Ein Abo, das sich automatisch verlängert, eine Versicherung, die Ihre Kündigung ablehnt, ein Fitnesscenter, das nicht reagiert: Wir prüfen Ihren Vertrag und verfassen eine Kündigung, die hält.",
    included: [
      "Prüfung der Kündigungsbedingungen",
      "Berechnung des möglichen Enddatums",
      "Versandbereites Kündigungsschreiben",
    ],
    needs: "Den Vertrag oder die AGB und das gewünschte Enddatum.",
    note: "Eine verspätete Kündigung wirkt erst auf den nächsten Termin. Versicherungsverträge können grundsätzlich auf Ende des dritten Jahres und danach jährlich gekündigt werden (Art. 35a VVG).",
    faq: [
      { q: "Der Anbieter lehnt meine Kündigung ab?", a: "Entspricht sie dem Vertrag, wirkt sie auch ohne seine Zustimmung. Der Brief hält das klar fest." },
      { q: "Kann ich aus wichtigem Grund kündigen?", a: "In gewissen Fällen ja. Beschreiben Sie Ihre Situation, wir prüfen es." },
    ],
  },
  "garantie-achat-defectueux": {
    name: "Defekter Kauf: Gewährleistung geltend machen",
    short: "Mahnung an den Verkäufer: Reparatur, Ersatz oder Rückerstattung, je nach Ihren Rechten.",
    intro: "Ein defektes Gerät, Möbel oder Fahrzeug, und der Verkäufer schiebt die Verantwortung ab? Wir prüfen Ihre Gewährleistungsrechte und verfassen die Mahnung.",
    included: [
      "Analyse der gesetzlichen und vertraglichen Garantie",
      "Wahl des günstigsten Begehrens: Reparatur, Ersatz, Minderung oder Wandelung",
      "Mahnung an den Verkäufer, versandbereit",
    ],
    needs: "Rechnung oder Quittung, Garantiebedingungen und Fotos des Mangels.",
    note: "Der Mangel ist dem Verkäufer sofort nach Entdeckung anzuzeigen (Art. 201 OR). Bei neuen Sachen für Konsumenten kann die zweijährige Frist nicht verkürzt werden (Art. 210 OR).",
    faq: [
      { q: "Der Verkäufer verweist auf den Hersteller?", a: "Die gesetzliche Gewährleistung bindet den Verkäufer. Der Brief hält fest, dass er Ihr Ansprechpartner bleibt." },
      { q: "Und bei Online-Käufen?", a: "Für Verkäufer in der Schweiz gelten dieselben Regeln. Bei ausländischen Verkäufern nennen wir das anwendbare Recht." },
    ],
  },
  "litige-artisan": {
    name: "Streit mit Handwerker oder Unternehmen",
    short: "Mangelhafte Arbeit, Verzug, überschrittene Offerte: Mängelrüge und Mahnung.",
    intro: "Schlampige Arbeit, endlose Baustelle, Rechnung weit über der Offerte: Wir prüfen Ihren Vertrag und verfassen Mängelrüge und Mahnung an den Handwerker.",
    included: [
      "Analyse von Vertrag, Offerte und Rechnungen",
      "Formgerechte Mängelrüge",
      "Mahnung: Nachbesserung, Frist oder Preisminderung",
    ],
    needs: "Offerte oder Vertrag, Rechnungen, Fotos und Korrespondenz.",
    note: "Mängel sind rasch nach Entdeckung zu rügen. Wird ein ungefährer Kostenansatz übermässig überschritten, können Sie Herabsetzung verlangen oder vom Vertrag zurücktreten (Art. 375 OR).",
    faq: [
      { q: "Muss ich die Rechnung vorerst zahlen?", a: "Wir sagen Ihnen, welchen Teil Sie zahlen und welchen Sie zurückbehalten können." },
      { q: "Und wenn die SIA-Norm 118 gilt?", a: "Wir berücksichtigen sie: Sie hat eigene Regeln und Fristen für Mängel." },
    ],
  },
  "contester-une-facture": {
    name: "Rechnung bestreiten",
    short: "Ungerechtfertigte oder überhöhte Rechnung: begründete schriftliche Bestreitung.",
    intro: "Eine Rechnung für nie bestellte Leistungen, ein aufgeblähter Betrag, überraschende Gebühren: Wir verfassen eine klare Bestreitung, die erklärt, warum Sie den Betrag nicht schulden.",
    included: [
      "Analyse der Rechnung und der Vereinbarung",
      "Begründetes Bestreitungsschreiben",
      "Vorgehen bei Mahnung oder Betreibung",
    ],
    needs: "Die bestrittene Rechnung, Vertrag oder Offerte und die Korrespondenz.",
    note: "Wer «um Ruhe zu haben» zahlt, anerkennt oft die Forderung. Bei einem Zahlungsbefehl haben Sie 10 Tage für den Rechtsvorschlag (Art. 74 SchKG).",
    faq: [
      { q: "Soll ich den unbestrittenen Teil zahlen?", a: "Ja, das zeigt Ihren guten Glauben. Der Brief nennt den anerkannten Betrag." },
      { q: "Und wenn mich das Unternehmen betreibt?", a: "Erheben Sie innert 10 Tagen Rechtsvorschlag. Siehe «Ungerechtfertigte Betreibung»." },
    ],
  },
  "relecture-contrat-particulier": {
    name: "Vertragsprüfung vor der Unterschrift",
    short: "Leasing, Kredit, Autokauf, Bauarbeiten: Wir prüfen und zeigen Ihnen die Fallen.",
    intro: "Lassen Sie wichtige Verträge vor der Unterschrift prüfen. Wir zeigen Ihnen ungünstige Klauseln, versteckte Kosten und Verhandlungsspielraum.",
    included: [
      "Vollständige Prüfung (bis 15 Seiten)",
      "Liste der Risiken und ungewöhnlichen Klauseln",
      "Änderungsvorschläge",
    ],
    needs: "Den Vertrag, die AGB und allenfalls die Offerte.",
    note: "Bei Leasing oder Konsumkredit können Sie Ihre Zustimmung innert 14 Tagen widerrufen (Art. 16 KKG).",
    faq: [
      { q: "Der Vertrag hat mehr als 15 Seiten?", a: "Bestellen Sie trotzdem: Wir bestätigen den genauen Preis vor Beginn." },
      { q: "Wie schnell?", a: "Drei Arbeitstage oder 24 Stunden mit Express." },
    ],
  },
  "vol-annule-retarde": {
    name: "Flug annulliert oder verspätet: Entschädigung",
    short: "Reklamation bei der Fluggesellschaft, zum Fixpreis, ohne Provision auf Ihre Entschädigung.",
    intro: "Annullierung, Überbuchung, grosse Verspätung: Vielleicht haben Sie Anspruch auf 250 bis 600 Euro pro Person. Wir prüfen Ihren Anspruch und verfassen die Reklamation, ohne Prozentabzug.",
    included: [
      "Prüfung des Anspruchs und der Höhe",
      "Reklamation an die Fluggesellschaft, versandbereit",
      "Vorgehen bei Ablehnung",
    ],
    needs: "Buchung, Bordkarte und die Mitteilungen der Fluggesellschaft.",
    note: "Die EU-Fluggastrechteverordnung gilt auch in der Schweiz, namentlich für Flüge ab Schweizer Flughäfen. Aussergewöhnliche Umstände (Wetter, Fluglotsenstreik) können die Entschädigung ausschliessen.",
    faq: [
      { q: "Warum keine Claims-Plattform?", a: "Diese behalten oft 25 bis 35 % der Entschädigung. Hier zahlen Sie einen Fixpreis und behalten den Rest." },
      { q: "Für mehrere Passagiere?", a: "Eine Bestellung genügt für alle Personen derselben Buchung." },
    ],
  },
  "refus-assurance": {
    name: "Ablehnung durch eine Versicherung: Reklamation",
    short: "Hausrat, Reise, Fahrzeug, Rechtsschutz: begründete Reklamation an den Versicherer.",
    intro: "Ihre Versicherung zahlt nicht oder nur teilweise? Wir analysieren Police und Entscheid und verfassen eine begründete Reklamation.",
    included: [
      "Analyse von Police, AVB und Ablehnung",
      "Rechtliche und vertragliche Argumente",
      "Reklamation an den Versicherer, versandbereit",
      "Vorgehen: Ombudsstelle, Verfahren",
    ],
    needs: "Police, AVB, Ablehnungsschreiben und Unterlagen zum Schadenfall.",
    note: "Forderungen aus dem Versicherungsvertrag verjähren grundsätzlich nach fünf Jahren (Art. 46 VVG). Der Ombudsman der Privatversicherung hilft kostenlos.",
    faq: [
      { q: "Und bei der Krankenkasse (KVG)?", a: "Das ist eine Sozialversicherung: siehe «Einsprache gegen einen Sozialversicherungsentscheid»." },
      { q: "Die Versicherung beruft sich auf einen Ausschluss?", a: "Nicht zwingend das Ende: Ausschlüsse müssen klar sein und werden im Zweifel zugunsten der versicherten Person ausgelegt." },
    ],
  },
  "poursuite-injustifiee": {
    name: "Ungerechtfertigte Betreibung: Rechtsvorschlag und Löschung",
    short: "Ungerechtfertigter Zahlungsbefehl: Rechtsvorschlag, danach Gesuch um Nichtbekanntgabe.",
    intro: "Sie haben einen Zahlungsbefehl für eine bestrittene Schuld erhalten? Wir erklären Ihnen den Rechtsvorschlag und verfassen danach das Gesuch um Nichtbekanntgabe, damit die Betreibung nicht mehr im Auszug erscheint.",
    included: [
      "Prüfung des Zahlungsbefehls und der Fristen",
      "Anleitung zum Rechtsvorschlag",
      "Gesuch um Nichtbekanntgabe an das Betreibungsamt, zum richtigen Zeitpunkt",
    ],
    needs: "Den Zahlungsbefehl (Foto oder PDF) und was Sie über die Forderung wissen.",
    note: "Der Rechtsvorschlag ist innert 10 Tagen ab Zustellung zu erheben (Art. 74 SchKG). Nach drei Monaten können Sie verlangen, dass die Betreibung Dritten nicht mehr bekanntgegeben wird, wenn der Gläubiger nichts unternommen hat (Art. 8a SchKG).",
    faq: [
      { q: "Kostet der Rechtsvorschlag etwas?", a: "Nein, er ist kostenlos und muss nicht begründet werden." },
      { q: "Verschwindet die Betreibung wirklich?", a: "Sie wird Dritten, etwa einem künftigen Vermieter, nicht mehr bekanntgegeben, wenn der Gläubiger das Verfahren nicht fortgesetzt hat." },
    ],
  },
  "recuperer-argent-prete": {
    name: "Geliehenes oder geschuldetes Geld zurückholen",
    short: "Mahnung und einreichebereites Betreibungsbegehren für ein Darlehen oder eine private Schuld.",
    intro: "Sie haben einer nahestehenden Person Geld geliehen, etwas verkauft ohne bezahlt zu werden oder Kosten vorgeschossen? Wir verfassen die Mahnung und bereiten das Betreibungsbegehren vor.",
    included: [
      "Prüfung der Beweise für die Forderung",
      "Mahnung mit Zahlungsfrist",
      "Vorbereitetes Betreibungsbegehren",
    ],
    needs: "Belege für das Darlehen oder die Schuld: Nachrichten, Überweisungen, Schuldanerkennung.",
    note: "Ein Darlehen ohne Fälligkeit ist innert sechs Wochen nach der ersten Aufforderung zurückzuzahlen (Art. 318 OR). Eine unterzeichnete Schuldanerkennung erleichtert die Fortsetzung stark (Art. 82 SchKG).",
    faq: [
      { q: "Ich habe keinen schriftlichen Vertrag?", a: "Nachrichten, Überweisungen und Zeugen können das Darlehen beweisen. Wir beurteilen Ihre Beweislage." },
      { q: "Und wenn der Schuldner Rechtsvorschlag erhebt?", a: "Dann braucht es die Rechtsöffnung oder eine Klage. Wir erklären Ihnen Ablauf und Kosten." },
    ],
  },
  "reclamation-taxation-impots": {
    name: "Einsprache gegen eine Steuerveranlagung",
    short: "Abzug verweigert, Einkommen falsch eingeschätzt: begründete Einsprache innert 30 Tagen.",
    intro: "Ihre Veranlagung entspricht nicht Ihrer Steuererklärung? Verweigerter Abzug, Ermessenseinschätzung, Rechenfehler: Wir verfassen eine begründete Einsprache.",
    included: [
      "Vergleich Steuererklärung / Veranlagung",
      "Argumente und Beilagen",
      "Versandbereite Einsprache",
    ],
    needs: "Die Veranlagungsverfügung, Ihre Steuererklärung und die betreffenden Belege.",
    note: "Die Einsprache ist innert 30 Tagen ab Eröffnung schriftlich und begründet einzureichen (Art. 132 DBG für die direkte Bundessteuer, ähnliche Regeln in den Kantonen).",
    faq: [
      { q: "Kann die Frist verlängert werden?", a: "Nein, sie ist gesetzlich. Wählen Sie Express, wenn das Datum naht." },
      { q: "Kann die Steuer nach einer Einsprache steigen?", a: "Die Behörde prüft die ganze Veranlagung neu: Wir prüfen dieses Risiko vorher." },
    ],
  },
  "opposition-assurance-sociale": {
    name: "Einsprache gegen einen Sozialversicherungsentscheid",
    short: "Arbeitslosenkasse, AHV, Krankenkasse, Unfall: begründete Einsprache innert 30 Tagen.",
    intro: "Einstelltage bei der Arbeitslosenversicherung, verweigerte Leistung der Krankenkasse, zu tiefe Rente: Wir analysieren den Entscheid und verfassen Ihre Einsprache.",
    included: [
      "Analyse des Entscheids und der Regeln",
      "Argumente und Beilagen",
      "Versandbereite Einsprache",
    ],
    needs: "Den Entscheid, die Korrespondenz und nützliche Unterlagen (Zeugnisse, Verträge, Bestätigungen).",
    note: "Die Einsprache ist innert 30 Tagen zu erheben (Art. 52 ATSG). Bei der IV gilt ein anderes Verfahren: Einwände zum Vorbescheid, danach Beschwerde.",
    faq: [
      { q: "Ist die Einsprache kostenlos?", a: "Ja, das Einspracheverfahren ist grundsätzlich kostenlos." },
      { q: "Und wenn sie abgewiesen wird?", a: "Innert 30 Tagen ist eine Beschwerde ans kantonale Gericht möglich. Wir sagen Ihnen, ob ein Anwalt empfehlenswert ist." },
    ],
  },
  testament: {
    name: "Testament: begleitete Redaktion",
    short: "Ein massgeschneidertes Testament nach neuem Erbrecht, zum Abschreiben von Hand.",
    intro: "Den Ehegatten begünstigen, die Partnerin schützen, einen bestimmten Gegenstand vermachen: Wir helfen Ihnen, ein klares Testament nach dem seit 2023 geltenden Erbrecht zu verfassen, das Sie von Hand abschreiben.",
    included: [
      "Berechnung der Pflichtteile und der verfügbaren Quote",
      "Testamentstext nach Ihren Wünschen",
      "Anleitung zum Abschreiben, Datieren, Unterzeichnen und Aufbewahren",
    ],
    needs: "Ihre Familiensituation, Ihre wichtigsten Vermögenswerte und was Sie wem vererben möchten.",
    note: "Ein eigenhändiges Testament muss vollständig von Hand geschrieben, datiert und unterzeichnet sein (Art. 505 ZGB). Seit 2023 haben Eltern keinen Pflichtteil mehr, und jener der Nachkommen beträgt die Hälfte ihres gesetzlichen Erbteils.",
    faq: [
      { q: "Braucht es einen Notar?", a: "Für ein eigenhändiges Testament nicht. Bei komplexen Verhältnissen ist eine öffentliche Beurkundung empfehlenswert." },
      { q: "Erbt mein unverheirateter Partner?", a: "Nein, ausser mit Testament. Genau das kann es vorsehen." },
    ],
  },
  "mandat-pour-cause-d-inaptitude": {
    name: "Vorsorgeauftrag",
    short: "Bestimmen Sie, wer für Sie entscheidet, wenn Sie es nicht mehr können: Vermögen, Gesundheit, Administratives.",
    intro: "Unfall, Krankheit: Können Sie Ihre Angelegenheiten nicht mehr regeln, bestimmt die Erwachsenenschutzbehörde jemanden. Mit einem Vorsorgeauftrag wählen Sie selbst. Wir verfassen ihn mit Ihnen.",
    included: [
      "Wahl der Bereiche: Personensorge, Vermögenssorge, Vertretung",
      "Auf Ihre Situation zugeschnittener Text",
      "Anleitung zu Form und Registrierung",
    ],
    needs: "Die gewählte(n) Person(en) und was Sie ihnen anvertrauen möchten.",
    note: "Der Vorsorgeauftrag ist eigenhändig zu errichten (von Hand geschrieben, datiert, unterzeichnet) oder öffentlich zu beurkunden (Art. 361 ZGB). Seine Hinterlegung kann beim Zivilstandsamt eingetragen werden.",
    faq: [
      { q: "Kann mich mein Ehegatte nicht schon vertreten?", a: "Nur für die gewöhnlichen Angelegenheiten (Art. 374 ZGB). Der Vorsorgeauftrag geht weiter." },
      { q: "Kann ich ihn ändern?", a: "Ja, jederzeit, solange Sie urteilsfähig sind." },
    ],
  },
  "directives-anticipees": {
    name: "Patientenverfügung",
    short: "Ihr medizinischer Wille, klar und gültig, und die Person, die ihn durchsetzt.",
    intro: "Welche Behandlungen möchten Sie annehmen oder ablehnen, wenn Sie sich nicht mehr äussern können? Die Patientenverfügung hält es klar fest und bezeichnet die Person, die für Sie spricht.",
    included: [
      "Geführter Fragebogen zu Ihren Wünschen",
      "Präzise formulierte Verfügung",
      "Bezeichnung einer vertretungsberechtigten Person",
    ],
    needs: "Ihre Wünsche und die Vertrauensperson, die Sie bezeichnen möchten.",
    note: "Die Patientenverfügung ist schriftlich zu errichten, zu datieren und zu unterzeichnen (Art. 371 ZGB). Sie kann auf der Versichertenkarte vermerkt werden.",
    faq: [
      { q: "Muss sich die Ärztin daran halten?", a: "Ja, ausser sie verstösst gegen das Gesetz oder entspricht nicht mehr Ihrem mutmasslichen Willen (Art. 372 ZGB)." },
      { q: "Braucht es einen Notar?", a: "Nein, schriftlich, datiert und unterzeichnet genügt." },
    ],
  },
  "convention-de-concubinage": {
    name: "Konkubinatsvertrag",
    short: "Wohnung, gemeinsame Kosten, Vermögen, Trennung: alles schwarz auf weiss geregelt.",
    intro: "Unverheiratete Paare sind gesetzlich kaum geschützt. Ein Konkubinatsvertrag regelt Wohnung, Ausgaben, gemeinsam gekaufte Gegenstände und die Trennung.",
    included: [
      "Analyse Ihrer gemeinsamen Situation",
      "Massgeschneiderter Vertrag: Wohnung, Kosten, Vermögen, Trennung",
      "Empfehlungen: Testament, Vorsorge, Versicherung",
    ],
    needs: "Ihre Situation: Wohnung, Einkommen, gemeinsames Vermögen, allfällige Kinder.",
    note: "Im Konkubinat erbt niemand ohne Testament, und die gemeinsame Wohnung ist nicht wie jene von Ehegatten geschützt.",
    faq: [
      { q: "Ist der Vertrag ohne Notar gültig?", a: "Ja, ein schriftlicher, von beiden unterzeichneter Vertrag genügt." },
      { q: "Und wenn wir Kinder haben?", a: "Wir nehmen die nützlichen Punkte auf und sagen Ihnen, was bei der Behörde zu regeln ist (elterliche Sorge, Unterhalt)." },
    ],
  },
  "separation-divorce-amiable": {
    name: "Einvernehmliche Scheidung ohne minderjährige Kinder",
    short: "Vereinbarung und gemeinsames Begehren, für Paare ohne minderjährige Kinder, die sich im Wesentlichen einig sind.",
    intro: "Sie sind sich im Wesentlichen einig, haben keine minderjährigen Kinder und möchten ein langes Verfahren vermeiden? Wir verfassen neutral und für Sie beide die Scheidungsvereinbarung und das gemeinsame Begehren, das Sie beim Gericht einreichen.",
    included: [
      "Vorgespräch mit beiden Ehegatten",
      "Vereinbarung: Wohnung, Unterhalt, Güter, Teilung der beruflichen Vorsorge",
      "Gemeinsames Scheidungsbegehren, einreichebereit, mit Beilagenliste",
    ],
    needs: "Einkommen, Vorsorgeausweise (2. Säule) beider Ehegatten und Vermögensliste.",
    note: "Die Scheidung auf gemeinsames Begehren erfordert keinen Anwalt: Die Ehegatten reichen Begehren und Vereinbarung selbst ein (Art. 111 ZGB). Das Gericht prüft, ob die Vereinbarung klar, vollständig und angemessen ist. Wir handeln neutral für beide Ehegatten und nur mit ihrem Einverständnis.",
    faq: [
      { q: "Und mit minderjährigen Kindern?", a: "Solche Fälle übernehmen wir nicht: Sorge, Obhut und Unterhalt gehören zu einer Familienmediation oder einem Anwalt. Wir weisen Ihnen den Weg." },
      { q: "Warum «ab CHF 590»?", a: "Der Preis gilt für einfache Verhältnisse ohne Liegenschaft oder Unternehmen. Er wird nach dem ersten Austausch schriftlich bestätigt, vor jeder Zahlung." },
    ],
  },
  "question-juridique": {
    name: "Rechtsfrage: schriftliche Antwort",
    short: "Eine präzise Frage, eine klare schriftliche Antwort mit den einschlägigen Gesetzesartikeln.",
    intro: "Sie haben eine präzise Frage und wollen eine verlässliche Antwort, ohne Termin? Stellen Sie sie: Sie erhalten eine klare schriftliche Antwort mit dem weiteren Vorgehen.",
    included: [
      "Rechtliche Abklärung Ihrer Frage",
      "Klare schriftliche Antwort mit Rechtsgrundlagen",
      "Empfohlener nächster Schritt",
    ],
    needs: "Ihre Frage und den Kontext in wenigen Zeilen.",
    note: "Eine Schnellfrage betrifft einen präzisen Punkt. Braucht Ihre Situation ein Dokument oder eine vollständige Analyse, schlagen wir Ihnen vorher die passende Leistung vor.",
    faq: [
      { q: "Und eine Rückfrage?", a: "Eine Präzisierung zur erhaltenen Antwort ist inbegriffen." },
      { q: "Welche Bereiche?", a: "Arbeit, Miete, Konsum, Verträge, Betreibung, einfaches Familienrecht. Im Strafrecht verweisen wir an einen Anwalt." },
    ],
  },
  "appel-juridique": {
    name: "Rechtsgespräch von 20 Minuten",
    short: "Sie schildern Ihre Situation, wir sagen Ihnen, was zu tun ist und innert welcher Fristen.",
    intro: "Sie sprechen lieber darüber? Buchen Sie ein Gespräch von 20 Minuten: Sie schildern Ihre Situation, wir sagen Ihnen, was Sie tun können, innert welcher Fristen und was zu vermeiden ist.",
    included: [
      "Telefon- oder Videogespräch von 20 Minuten",
      "Vorbereitung anhand Ihrer schriftlichen Beschreibung",
      "Schriftliche Zusammenfassung der nächsten Schritte",
    ],
    needs: "Eine Beschreibung Ihrer Situation und Ihre Verfügbarkeiten.",
    note: "Bestellen Sie innert 30 Tagen eine damit zusammenhängende Leistung, wird der Preis des Gesprächs angerechnet.",
    faq: [
      { q: "Wann findet das Gespräch statt?", a: "Wir schlagen Termine innert zwei Arbeitstagen vor." },
      { q: "Und wenn 20 Minuten nicht reichen?", a: "Die Zusammenfassung nennt die passende Leistung und ihren Fixpreis." },
    ],
  },
  "lettre-juridique-sur-mesure": {
    name: "Massgeschneiderter Rechtsbrief",
    short: "Ein formeller Brief für Ihre Situation, rechtlich begründet und versandbereit.",
    intro: "Ihre Situation passt in kein Raster? Wir verfassen den formellen Brief, den Sie brauchen: Reklamation, Bestreitung, Gesuch, Mahnung.",
    included: [
      "Analyse Ihrer Situation",
      "Rechtlich begründeter, versandbereiter Brief",
      "Eine Korrekturrunde",
    ],
    needs: "Ihre Situation, den Empfänger und die nützlichen Unterlagen.",
    note: "Ein guter Brief setzt eine Frist, nennt die richtigen Regeln und hinterlässt eine schriftliche Spur für ein allfälliges Verfahren.",
    faq: [
      { q: "Wird der Brief von Thrax Legal unterzeichnet?", a: "Nein, er wird in Ihrem Namen verfasst und Sie versenden ihn selbst." },
      { q: "Und wenn es komplexer ist?", a: "Wir sagen es Ihnen vorher und nennen den passenden Preis." },
    ],
  },
  "mise-en-demeure": {
    name: "Mahnung an einen Kunden",
    short: "Formelles Schreiben mit Frist, Zinsen und angekündigten Folgen: die letzte Warnung vor der Betreibung.",
    intro: "Ein Kunde zahlt trotz Erinnerungen nicht? Eine formelle Mahnung mit Frist, Verzugszinsen und angekündigten Folgen löst die Zahlung oft aus.",
    included: [
      "Prüfung der Forderung und der Belege",
      "Berechnung der Verzugszinsen",
      "Versandbereite Mahnung auf Ihrem Briefkopf",
    ],
    needs: "Die offene Rechnung, Vertrag oder Auftragsbestätigung und Ihre Erinnerungen.",
    note: "Ab Verzug ist ein Verzugszins von 5 % pro Jahr geschuldet (Art. 104 OR). War ein bestimmter Verfalltag vereinbart, tritt der Verzug mit dessen Ablauf ein (Art. 102 OR).",
    faq: [
      { q: "Eingeschrieben senden?", a: "Empfehlenswert, um den Empfang zu beweisen. Ein paralleler E-Mail-Versand beschleunigt oft die Zahlung." },
      { q: "Und wenn der Kunde immer noch nicht zahlt?", a: "Wechseln Sie zum vollständigen Inkasso: Betreibungsbegehren und weiteres Verfahren." },
    ],
  },
  "recouvrement-facture-impayee": {
    name: "Inkasso einer unbezahlten Rechnung",
    short: "Mahnung, vorbereitetes Betreibungsbegehren, Begleitung beim Rechtsvorschlag: Wir kümmern uns um alles.",
    intro: "Eine Rechnung ist seit Wochen offen? Wir übernehmen den ganzen aussergerichtlichen Weg und die Vorbereitung der Betreibung, bis zum Rechtsöffnungsgesuch, falls der Schuldner Rechtsvorschlag erhebt.",
    included: [
      "Mahnung mit Zinsen",
      "Vorbereitetes, einreichebereites Betreibungsbegehren",
      "Analyse eines allfälligen Rechtsvorschlags und der nächsten Schritte",
      "Tipps zur Wahrung der Kundenbeziehung, wo möglich",
    ],
    needs: "Rechnung, Vertrag oder Bestellung, Ihre Erinnerungen und die Angaben des Schuldners.",
    note: "Forderungen verjähren in der Regel nach zehn Jahren, viele alltägliche Leistungen aber nach fünf Jahren (Art. 127 und 128 OR). Sie reichen das Begehren selbst ein: Die berufsmässige Vertretung vor Betreibungsämtern ist kantonal geregelt.",
    faq: [
      { q: "Warum kein Inkassobüro?", a: "Diese nehmen einen Prozentsatz oder belasten dem Schuldner Gebühren, teils umstritten. Hier ist der Preis fix und die Kundenbeziehung bleibt gewahrt." },
      { q: "Mehrere Rechnungen desselben Kunden?", a: "Eine Leistung deckt alle Rechnungen desselben Schuldners." },
    ],
  },
  "requete-de-mainlevee": {
    name: "Rechtsöffnungsgesuch",
    short: "Nach dem Rechtsvorschlag: einreichebereites Rechtsöffnungsgesuch mit geordneten Beilagen.",
    intro: "Ihr Schuldner hat Rechtsvorschlag erhoben? Mit einer Schuldanerkennung oder einem Urteil können Sie die Betreibung mit der Rechtsöffnung fortsetzen. Wir verfassen das Gesuch.",
    included: [
      "Prüfung des Titels: Schuldanerkennung oder Urteil",
      "Gesuch um provisorische oder definitive Rechtsöffnung",
      "Beilagenverzeichnis",
    ],
    needs: "Zahlungsbefehl mit Rechtsvorschlag, unterzeichneten Vertrag oder Schuldanerkennung und Rechnungen.",
    note: "Eine unterzeichnete Schuldanerkennung ermöglicht die provisorische (Art. 82 SchKG), ein vollstreckbares Urteil die definitive Rechtsöffnung (Art. 80 SchKG). Ohne Titel ist eine Anerkennungsklage nötig.",
    faq: [
      { q: "Genügt ein unterzeichneter Vertrag?", a: "Oft ja, wenn die Leistung erbracht wurde und der Betrag klar aus dem Vertrag hervorgeht." },
      { q: "Wer reicht das Gesuch ein?", a: "Sie, beim zuständigen Gericht. Wir sagen Ihnen, welches und wie." },
    ],
  },
  "litige-commercial": {
    name: "Geschäftsstreit: Analyse und Schreiben",
    short: "Kunde, Lieferant oder Partner: Ihre Position analysiert und schriftlich verteidigt.",
    intro: "Mangelhafte Lieferung, bestrittene Leistung, Vertragsbruch: Wir analysieren die Situation und verfassen das Schreiben, das Ihre Position verteidigt und eine Lösung ermöglicht.",
    included: [
      "Analyse von Vertrag und Korrespondenz",
      "Beurteilung Ihrer Position und der Risiken",
      "Formelles Schreiben an die Gegenpartei",
    ],
    needs: "Vertrag, Rechnungen und wichtige Korrespondenz.",
    note: "Schriftliches zählt: Ein präzises, früh versandtes Schreiben stärkt Ihre Position in einem Verfahren.",
    faq: [
      { q: "Und wenn es vor Gericht geht?", a: "Wir verweisen Sie an einen Anwalt und übergeben ihm ein sauberes Dossier." },
      { q: "Können Sie für uns verhandeln?", a: "Wir bereiten Ihre Schreiben und Argumente vor; Sie bleiben Ansprechpartner." },
    ],
  },
  "cgv-sur-mesure": {
    name: "Massgeschneiderte AGB",
    short: "AGB für Ihre Tätigkeit: Zahlung, Haftung, Gewährleistung, Gerichtsstand.",
    intro: "Von der Konkurrenz kopierte AGB schützen Sie nicht. Wir verfassen AGB, die zu Ihrer Tätigkeit, Ihren Kunden (Unternehmen oder Konsumenten) und Ihrer Verkaufsart passen.",
    included: [
      "Fragebogen zu Tätigkeit und Risiken",
      "Vollständige AGB: Bestellung, Preis, Zahlung, Verzug, Gewährleistung, Haftung, Gerichtsstand",
      "Hinweise zur gültigen Einbindung (Website, Offerten, Rechnungen)",
      "Eine Korrekturrunde",
    ],
    needs: "Eine Beschreibung Ihrer Tätigkeit und Ihre aktuellen Dokumente (Offerte, Rechnung, bestehende AGB).",
    note: "AGB gelten nur, wenn der Kunde vor Vertragsschluss davon Kenntnis nehmen konnte. Gegenüber Konsumenten sind unausgewogene Klauseln unlauter (Art. 8 UWG).",
    faq: [
      { q: "Braucht der Onlineshop eigene AGB?", a: "Oft ja, oder ein eigenes Kapitel. Wir nehmen es auf, wenn Sie online verkaufen." },
      { q: "In welchen Sprachen?", a: "Standardmässig auf Französisch. Eine Übersetzung ist auf Offerte möglich." },
    ],
  },
  "contrat-commercial-sur-mesure": {
    name: "Massgeschneiderter Geschäftsvertrag",
    short: "Dienstleistung, Unterakkord, Vertrieb, Partnerschaft: ein Vertrag für Ihre Situation.",
    intro: "Eine wichtige Vereinbarung verdient einen echten Vertrag. Wir verfassen einen Vertrag für Ihre Geschäftsbeziehung mit den Klauseln, die Ihre Interessen schützen.",
    included: [
      "Klärung der Vereinbarung und der Risiken",
      "Vollständiger Vertrag: Gegenstand, Preis, Fristen, Haftung, Kündigung, Gerichtsstand",
      "Eine Korrekturrunde",
    ],
    needs: "Die mit dem Partner vereinbarten Punkte und Ihre bestehenden Dokumente.",
    note: "Die meisten Geschäftsverträge sind formfrei, doch ein klarer Text verhindert die meisten Streitigkeiten.",
    faq: [
      { q: "Und wenn die Gegenpartei ihren eigenen Vertrag vorlegt?", a: "Wählen Sie dann die Prüfung eines Geschäftsvertrags." },
      { q: "Vertrag auf Englisch?", a: "Möglich, Preis vor Beginn bestätigt." },
    ],
  },
  "relecture-contrat-commercial": {
    name: "Prüfung eines Geschäftsvertrags",
    short: "Risiken markiert und Korrekturen vorgeschlagen, vor der Unterschrift (bis 20 Seiten).",
    intro: "Ein Kunde oder Lieferant legt Ihnen seinen Vertrag vor? Wir prüfen ihn, markieren gefährliche Klauseln und schlagen Korrekturen für die Verhandlung vor.",
    included: [
      "Vollständige Prüfung (bis 20 Seiten)",
      "Nach Priorität geordnete Risiken",
      "Korrekturvorschläge im Änderungsmodus",
    ],
    needs: "Den Vertrag (idealerweise Word) und den Kontext der Beziehung.",
    note: "Haftungs-, Konventionalstrafen-, Laufzeit- und Gerichtsstandsklauseln kosten im Streitfall am meisten.",
    faq: [
      { q: "Mehr als 20 Seiten?", a: "Der Preis wird vorab bestätigt, pro angefangene 20 Seiten." },
      { q: "Vertrag auf Englisch?", a: "Ja, die Prüfung auf Englisch ist möglich." },
    ],
  },
  "accord-de-confidentialite": {
    name: "Geheimhaltungsvereinbarung (NDA)",
    short: "Einseitig oder gegenseitig, auf Ihr Projekt zugeschnitten, mit abschreckender Konventionalstrafe.",
    intro: "Bevor Sie ein Projekt, Know-how oder Zahlen präsentieren: Schützen Sie sie. Wir verfassen eine Geheimhaltungsvereinbarung für Ihre Situation.",
    included: [
      "Wahl zwischen einseitiger und gegenseitiger Vereinbarung",
      "Präzise Definition der geschützten Informationen",
      "Passende Konventionalstrafe und Dauer",
    ],
    needs: "Die Parteien, das Projekt und die zu schützenden Informationen.",
    note: "Eine Konventionalstrafe (Art. 160 ff. OR) erspart den Nachweis der genauen Schadenshöhe bei einer Verletzung.",
    faq: [
      { q: "Genügt nicht eine Gratisvorlage?", a: "Oft schützt sie schlecht, was für Sie zählt, oder sieht eine unanwendbare Strafe vor." },
      { q: "Auf Englisch?", a: "Ja, ohne Aufpreis für ein Standard-NDA." },
    ],
  },
  "contrat-de-mandat-independant": {
    name: "Auftragsvertrag für Selbstständige",
    short: "Auftrag, Honorar, Haftung, geistiges Eigentum: ein solider Freelance-Vertrag.",
    intro: "Ob Sie Freelancer sind oder eine selbstständige Person beauftragen: Ein klarer Vertrag vermeidet Missverständnisse und das Risiko einer Umqualifizierung in einen Arbeitsvertrag.",
    included: [
      "Auftrag oder Werkvertrag je nach Mission",
      "Klauseln zu Honorar, Haftung und geistigem Eigentum",
      "Hinweise zum Status als Selbstständige(r)",
    ],
    needs: "Mission, Dauer, Honorar und Parteien.",
    note: "Der AHV-Status hängt von der tatsächlichen Zusammenarbeit ab, nicht nur vom Vertrag. Ein Auftrag kann jederzeit von beiden Seiten aufgelöst werden (Art. 404 OR).",
    faq: [
      { q: "Auftrag oder Werkvertrag?", a: "Je nach versprochenem Ergebnis. Wir wählen die passende Qualifikation und erklären sie." },
      { q: "Für mehrere Kunden?", a: "Wir können eine wiederverwendbare Vorlage verfassen; vermerken Sie es in Ihrer Anfrage." },
    ],
  },
  "contrat-de-travail-sur-mesure": {
    name: "Massgeschneiderter Arbeitsvertrag",
    short: "Auf Stelle und Gesamtarbeitsvertrag zugeschnitten, mit den Klauseln, die das Unternehmen schützen.",
    intro: "Ein gut formulierter Arbeitsvertrag verhindert die meisten Streitigkeiten: Arbeitszeit, Überstunden, Ferien, Konkurrenzverbot, Geheimhaltung. Wir verfassen ihn für die betreffende Stelle.",
    included: [
      "Prüfung des anwendbaren Gesamtarbeitsvertrags",
      "Vollständiger, auf die Stelle zugeschnittener Vertrag",
      "Unverzichtbare Schriftklauseln: Überstunden, Konkurrenzverbot, Geheimhaltung",
      "Eine Korrekturrunde",
    ],
    needs: "Stelle, Pensum, Lohn, Eintrittsdatum und Ihre internen Gepflogenheiten.",
    note: "Gewisse Klauseln gelten nur schriftlich, etwa der Ausschluss der Überstundenentschädigung (Art. 321c OR) oder das Konkurrenzverbot (Art. 340 OR). Ein allgemeinverbindlicher GAV gilt auch ohne Mitgliedschaft.",
    faq: [
      { q: "Eine Vorlage für mehrere Mitarbeitende?", a: "Ja, wir können eine Vorlage für mehrere ähnliche Stellen verfassen; vermerken Sie es in Ihrer Anfrage." },
      { q: "Und für Lernende?", a: "Der Lehrvertrag folgt einem kantonalen amtlichen Formular; wir weisen Ihnen den Weg." },
    ],
  },
  "certificat-de-travail-employeur": {
    name: "Arbeitszeugnis verfassen",
    short: "Vollständig, wahr und wohlwollend, ohne Formulierungen, die sich gegen Sie wenden.",
    intro: "Ein Arbeitszeugnis zu schreiben braucht Zeit und birgt Fallen: Zu schmeichelhaft begründet es Haftung, zu streng einen Streit. Wir verfassen es nach Ihren Angaben.",
    included: [
      "Kurzer Fragebogen zur Person",
      "Vollzeugnis oder Arbeitsbestätigung",
      "Praxisgerechte Formulierungen",
    ],
    needs: "Stelle, Daten, Hauptaufgaben und Ihre Beurteilung von Leistung und Verhalten.",
    note: "Das Zeugnis muss vollständig, wahr und wohlwollend sein (Art. 330a OR). Ein beschönigendes Zeugnis kann Ihre Haftung gegenüber einem künftigen Arbeitgeber begründen.",
    faq: [
      { q: "Zwischenzeugnis?", a: "Ja, zum gleichen Preis." },
      { q: "Wie schnell?", a: "Zwei Arbeitstage oder 24 Stunden mit Express." },
    ],
  },
  "licenciement-employeur": {
    name: "Sichere Kündigung",
    short: "Frist geprüft, Sperrfristen kontrolliert, korrektes Kündigungsschreiben.",
    intro: "Eine schlecht vorbereitete Kündigung kann nichtig oder missbräuchlich sein. Wir prüfen Fristen und Sperrfristen und verfassen Kündigungsschreiben und schriftliche Begründung.",
    included: [
      "Prüfung der Kündigungsfrist und des Enddatums",
      "Kontrolle der Sperrfristen",
      "Kündigungsschreiben und schriftliche Begründung",
      "Hinweise: Feriensaldo, Zeugnis, Versicherungen",
    ],
    needs: "Arbeitsvertrag, Situation der Person (Absenzen, Schwangerschaft …) und Grund.",
    note: "Eine Kündigung während einer Sperrfrist (Krankheit, Unfall, Schwangerschaft, Dienst) ist nichtig (Art. 336c OR). Eine missbräuchliche Kündigung kann bis zu sechs Monatslöhne kosten (Art. 336a OR).",
    faq: [
      { q: "Und eine fristlose Kündigung?", a: "Sie verlangt wichtige Gründe (Art. 337 OR), oft nach einer Verwarnung. Wir beurteilen zuerst das Risiko." },
      { q: "Braucht es ein Gespräch vorher?", a: "Meist nicht vorgeschrieben, aber empfohlen. Wir geben Ihnen einen Leitfaden." },
    ],
  },
  "avertissement-employe": {
    name: "Schriftliche Verwarnung",
    short: "Fakten, Erwartungen, Konsequenzen: eine Verwarnung, die im Streitfall hält.",
    intro: "Wiederholte Verspätungen, unangemessenes Verhalten, missachtete Weisungen: Eine präzise, verhältnismässige schriftliche Verwarnung schützt das Unternehmen, falls es zur Kündigung kommt.",
    included: [
      "Sachliche Beschreibung der Verfehlungen",
      "Klare Erwartungen und angekündigte Konsequenzen",
      "Übergabebereite Verwarnung",
    ],
    needs: "Die Fakten, Daten und allfällige frühere Verwarnungen.",
    note: "Bei mittelschweren Verfehlungen setzt eine fristlose Kündigung grundsätzlich eine erfolglose Verwarnung voraus.",
    faq: [
      { q: "Muss die Person unterschreiben?", a: "Eine Empfangsbestätigung ist nützlich; sonst vor Zeugen übergeben." },
      { q: "Wie lange bleibt sie gültig?", a: "Es gibt keine feste Dauer; je älter, desto weniger Gewicht." },
    ],
  },
  "reglement-du-personnel": {
    name: "Personalreglement",
    short: "Arbeitszeit, Ferien, Spesen, Homeoffice, Daten: klare Regeln für das ganze Team.",
    intro: "Schon ab wenigen Mitarbeitenden erspart ein Personalreglement das Neuverhandeln jeder Regel. Wir verfassen es für Ihr Unternehmen, abgestimmt auf Verträge und GAV.",
    included: [
      "Fragebogen zu Ihren Gepflogenheiten",
      "Vollständiges Reglement: Arbeitszeit, Absenzen, Spesen, Homeoffice, IT, Daten",
      "Hinweise zu Einführung und Kommunikation",
      "Eine Korrekturrunde",
    ],
    needs: "Ihre Musterverträge, Ihre Gepflogenheiten und den anwendbaren GAV.",
    note: "Das Reglement muss den Mitarbeitenden bekanntgegeben und in die Verträge einbezogen werden, um verbindlich zu sein.",
    faq: [
      { q: "Ab wie vielen Mitarbeitenden?", a: "Ab zwei oder drei spart es Zeit und vermeidet Ungleichbehandlungen." },
      { q: "Kann man es später ändern?", a: "Ja, unter Einhaltung der Fristen für Änderungen der Arbeitsbedingungen." },
    ],
  },
  "pack-conformite-nlpd": {
    name: "DSG-Compliance-Paket",
    short: "Datenschutzerklärung, Bearbeitungsverzeichnis, Klauseln: Ihre Umsetzung des neuen DSG.",
    intro: "Seit dem 1. September 2023 gilt das neue Datenschutzgesetz für alle Unternehmen. Wir erfassen Ihre Bearbeitungen und verfassen die wesentlichen Dokumente.",
    included: [
      "Geführte Erfassung Ihrer Bearbeitungen und Auftragsbearbeiter",
      "Datenschutzerklärung für Website und Kunden",
      "Verzeichnis der Bearbeitungstätigkeiten",
      "Klauseln für Ihre Verträge und Auftragsbearbeiter",
    ],
    needs: "Ihre Website, Ihre Tools (CRM, Newsletter, Buchhaltung, Cloud) und Ihre Datenarten.",
    note: "Sie müssen betroffene Personen über die Beschaffung ihrer Daten informieren (Art. 19 DSG). Vorsätzliche Verletzungen gewisser Pflichten werden mit Busse bis CHF 250'000 gegen die Verantwortlichen bestraft (Art. 60 DSG).",
    faq: [
      { q: "Ist das Verzeichnis für KMU Pflicht?", a: "Unter 250 Mitarbeitenden nicht immer, aber es ist der beste Nachweis der Konformität und wird oft von Kunden verlangt." },
      { q: "Und die DSGVO?", a: "Gilt sie für Sie, berücksichtigen wir sie in den Dokumenten." },
    ],
  },
  "politique-de-confidentialite": {
    name: "Datenschutzerklärung der Website",
    short: "DSG-konform, auf Ihre Tools abgestimmt: Formulare, Analytics, Newsletter.",
    intro: "Ihre Website erhebt Daten über ein Formular, Statistiken oder einen Newsletter? Sie braucht eine genaue Datenschutzerklärung, abgestimmt auf Ihre tatsächlichen Tools.",
    included: [
      "Erfassung der Website-Tools",
      "Vollständige Datenschutzerklärung",
      "Impressum der Website",
    ],
    needs: "Die Website-Adresse und die Liste Ihrer Tools (Hosting, Analytics, Formulare, Newsletter).",
    note: "Eine generische Erklärung, die nicht Ihren tatsächlichen Bearbeitungen entspricht, erfüllt die Informationspflicht nicht (Art. 19 DSG).",
    faq: [
      { q: "Und Cookies?", a: "Wir sagen Ihnen, ob ein Banner nach Ihren Tools nötig ist." },
      { q: "Mehrsprachig?", a: "Übersetzung möglich, Preis vor Beginn bestätigt." },
    ],
  },
  "relecture-bail-commercial": {
    name: "Prüfung eines Geschäftsmietvertrags",
    short: "Miete, Indexierung, Dauer, Instandstellung: die Verhandlungspunkte vor der Unterschrift.",
    intro: "Ein Geschäftsmietvertrag bindet Sie oft fünf Jahre oder länger. Wir prüfen ihn und zeigen Ihnen ungünstige Klauseln und Verhandlungspunkte.",
    included: [
      "Vollständige Prüfung von Vertrag und Anhängen",
      "Verhandlungspunkte: Miete, Indexierung, Dauer, Optionen, Arbeiten, Instandstellung",
      "Fragenliste für den Vermieter",
    ],
    needs: "Den Vertragsentwurf, die Anhänge und allenfalls das Antrittsprotokoll.",
    note: "Auch der Anfangsmietzins eines Geschäftslokals kann innert 30 Tagen angefochten werden (Art. 270 OR). Die Kautionsgrenze von drei Monatsmieten gilt nur für Wohnungen.",
    faq: [
      { q: "Und wenn ich schon unterschrieben habe?", a: "Die Prüfung zeigt Ihnen Ihre Rechte und die zu beachtenden Fristen." },
      { q: "Geschäftsübernahme?", a: "Vermerken Sie es: Vertragsübernahme und Ablöse werden analysiert." },
    ],
  },
  "convention-d-actionnaires": {
    name: "Aktionärbindungs- oder Gesellschaftervertrag",
    short: "Governance, Ausstieg, Vorkaufsrecht, Konkurrenzverbot: die Regeln unter Gesellschaftern.",
    intro: "Die Statuten regeln nicht alles. Ein Aktionärbindungs- oder Gesellschaftervertrag ordnet Entscheide, Ein- und Austritt und schützt alle bei Uneinigkeit.",
    included: [
      "Vorgespräch",
      "Vollständiger Vertrag: Governance, Übertragung, Vorkaufsrecht, Ausstieg, Konkurrenzverbot",
      "Konventionalstrafen und Pattsituationen",
      "Eine Korrekturrunde",
    ],
    needs: "Die Statuten, die Kapitalverteilung und die heiklen Punkte unter Gesellschaftern.",
    note: "Der Vertrag bindet die Gesellschafter untereinander, nicht die Gesellschaft: Konventionalstrafen sichern seine Einhaltung.",
    faq: [
      { q: "Mehr als drei Gesellschafter?", a: "Der Preis wird vor Beginn bestätigt." },
      { q: "Braucht es einen Notar?", a: "Für den Vertrag nicht; Statutenänderungen einer AG oder GmbH erfordern eine öffentliche Urkunde." },
    ],
  },
  "statuts-d-association": {
    name: "Vereinsstatuten",
    short: "ZGB-konform, auf Ihr Projekt zugeschnitten: Zweck, Organe, Mitglieder, Finanzen.",
    intro: "Sportclub, Kulturverein, Quartierprojekt: Wir verfassen klare, ZGB-konforme Statuten und das Protokoll der Gründungsversammlung.",
    included: [
      "Vollständige Statuten",
      "Protokoll der Gründungsversammlung",
      "Hinweise zum Handelsregistereintrag, falls nötig",
    ],
    needs: "Den Vereinszweck, die Gründungsmitglieder und die gewünschte Organisation.",
    note: "Die Statuten müssen schriftlich sein und über Zweck, Mittel und Organisation Aufschluss geben (Art. 60 ZGB).",
    faq: [
      { q: "Ist der Handelsregistereintrag Pflicht?", a: "Nur in gewissen Fällen (kaufmännisches Gewerbe, Revisionspflicht). Wir sagen es Ihnen." },
      { q: "Kann man die Statuten später ändern?", a: "Ja, durch Beschluss der Generalversammlung." },
    ],
  },
};

export const SERVICE_TEXT_DE = { services, categories };
