import type { CategoryId } from "@/lib/services/catalog";
import type { CategoryText, ServiceText } from "./types";

const categories: Record<CategoryId, CategoryText> = {
  travail: { name: "Employment", lead: "Your rights towards your employer" },
  logement: { name: "Housing & neighbours", lead: "Rent, defects, deposit, notice" },
  consommation: { name: "Purchases, contracts & travel", lead: "Warranty, cancellation, refunds" },
  argent: { name: "Money & debt collection", lead: "Get your money back, challenge a debt enforcement" },
  administration: { name: "Tax & social insurance", lead: "Decisions to challenge within 30 days" },
  famille: { name: "Family & future", lead: "Protect your loved ones and your wishes" },
  "sur-mesure": { name: "Tailor-made", lead: "Your situation is not on the list" },
  recouvrement: { name: "Debt collection & disputes", lead: "Get clients to pay, defend your position" },
  contrats: { name: "Contracts & T&Cs", lead: "Contracts that actually protect you" },
  employeurs: { name: "Employers", lead: "Hire, manage and part ways safely" },
  conformite: { name: "Compliance & company", lead: "FADP, commercial lease, partners" },
};

const services: Record<string, ServiceText> = {
  "analyse-certificat-de-travail": {
    name: "Work reference analysis",
    short: "Every phrase of your work reference decoded: what helps you, what hurts you, what is missing.",
    intro: "A work reference can look positive and still contain coded phrases, omissions or nuances that hold back your applications. We analyse it sentence by sentence and tell you what it really says to recruiters.",
    included: [
      "Review of every sentence, including coded phrases and omissions",
      "Overall rating: very good, good, average or to be corrected",
      "List of points you are entitled to have changed",
      "Clear recommendation: keep it or request a correction",
    ],
    needs: "Your work reference (legible photo or PDF) and, if possible, your job description.",
    note: "Your employer must give you a complete, accurate and benevolently worded reference covering the nature and length of employment, the quality of your work and your conduct (art. 330a CO). You can also ask for an interim reference at any time.",
    faq: [
      { q: "What is a coded phrase?", a: "A seemingly positive sentence that signals a weakness to recruiters, such as being satisfied \"on the whole\". The analysis spots and explains them." },
      { q: "What if the reference needs correcting?", a: "You can move on to the correction request: the price of the analysis is deducted if you order within 30 days." },
    ],
  },
  "rectification-certificat-de-travail": {
    name: "Work reference: correction request",
    short: "Analysis of your reference and a letter to your employer with the rewording you can demand.",
    intro: "Your reference contains vague phrases, omissions or sentences that work against you? We analyse it sentence by sentence and write the letter to your employer with the rewording you are entitled to request.",
    included: [
      "Full analysis of the reference, coded phrases and omissions included",
      "Proposed corrected text, sentence by sentence",
      "Correction request letter, ready to send",
      "Next steps if the employer refuses",
    ],
    needs: "Your work reference, your contract if you have it, and two lines on what bothers you.",
    note: "The reference must be complete, accurate and benevolent (art. 330a CO). If the employer refuses, you can sue for correction: employment disputes up to CHF 30,000 are free of court costs (art. 114 CPC).",
    faq: [
      { q: "Will my employer know you are helping me?", a: "No. The letter is written in your name and you send it yourself." },
      { q: "Can my employer refuse?", a: "They cannot refuse to correct an inaccurate or incomplete statement. If they refuse without reason, the letter prepares the next step and we explain your options." },
    ],
  },
  "licenciement-opposition": {
    name: "Dismissal: review and objection",
    short: "Notice periods, protection periods, abusive dismissal: we check your dismissal and write the objection.",
    intro: "You have just been dismissed and something doesn't feel right? We check whether the notice respects the deadlines, falls within a protection period or may be abusive, then write your written objection.",
    included: [
      "Check of the notice period and end date",
      "Review of protection periods: illness, accident, pregnancy, military service",
      "Analysis of the reason: abusive or not",
      "Objection letter and request for written reasons, ready to send",
    ],
    needs: "The dismissal letter, your employment contract and the key dates (sick leave, meetings…).",
    note: "To claim compensation for abusive dismissal, you must object in writing before the end of the notice period, then sue within 180 days after the contract ends (art. 336b CO). Notice given during a protection period is void (art. 336c CO).",
    faq: [
      { q: "How long do I have?", a: "The objection must reach the employer before the notice period ends. Choose the express option if the date is close." },
      { q: "Do I get my job back?", a: "Under Swiss law, an abusive dismissal remains valid: it entitles you to compensation of up to six months' salary. Notice given during a protection period, however, is void." },
    ],
  },
  "relecture-contrat-de-travail": {
    name: "Employment contract review",
    short: "Before you sign: probation, overtime, non-compete, holidays, all checked.",
    intro: "You've been offered a contract and want to know what you're signing? We review it and flag unfavourable, unusual or void clauses, with what you can negotiate.",
    included: [
      "Full review of the contract (up to 15 pages)",
      "Risk points flagged: probation, overtime, non-compete, mobility, holidays",
      "Comparison with the applicable collective agreement, if any",
      "Suggested changes to request before signing",
    ],
    needs: "The proposed contract and, if you have it, the job offer or advert.",
    note: "The probation period cannot exceed three months (art. 335b CO). A non-compete clause is only valid in writing and if you have access to clients or trade secrets (art. 340 CO).",
    faq: [
      { q: "Can I negotiate my contract?", a: "Yes, before signing. We give you the priority points and polite wording to raise them." },
      { q: "What if I have already signed?", a: "The review is still useful: some clauses are void even when signed. We tell you which ones." },
    ],
  },
  "salaire-impaye": {
    name: "Unpaid salary, overtime or holidays",
    short: "Calculation of what you are owed and a formal notice to your employer with a payment deadline.",
    intro: "Late salary, overtime never paid, holiday balance ignored at the end of the contract: we calculate exactly what you are owed and write the formal notice to your employer.",
    included: [
      "Detailed calculation (salary, hours, holidays, 13th month)",
      "Check of contract and collective agreement rules",
      "Formal notice with payment deadline, ready to send",
      "Next steps if the employer does not pay",
    ],
    needs: "Your contract, your payslips and, if you have it, a record of your hours.",
    note: "Overtime is paid with a 25% supplement unless otherwise agreed in writing (art. 321c CO). Salary claims expire after five years (art. 128 CO): don't wait.",
    faq: [
      { q: "Can I claim while still working there?", a: "Yes. The letter is firm but correct, to preserve the relationship if you stay." },
      { q: "What if the employer doesn't respond?", a: "You can apply to the conciliation authority. We can draft the application: see \"Conciliation application (employment)\"." },
    ],
  },
  "lettre-de-demission": {
    name: "Resignation letter",
    short: "The right notice, the right end date, your holiday balance and the reference request.",
    intro: "A wrongly dated resignation can cost you a month's salary or create needless conflict. We calculate your notice and write a clear letter that also settles remaining holidays and your work reference.",
    included: [
      "Calculation of the notice period and exact end date",
      "Personalised resignation letter",
      "Reference request and holiday balance",
    ],
    needs: "Your employment contract and the date you wish to leave.",
    note: "Unless otherwise agreed, notice is one month in the first year, two months from the second to the ninth year and three months thereafter, to the end of a month (art. 335c CO). The letter must reach the employer before the notice starts.",
    faq: [
      { q: "Can I leave earlier?", a: "Only with the employer's agreement. The letter can propose an earlier date while respecting the legal notice." },
      { q: "Should I send it by registered mail?", a: "Recommended to prove receipt, or hand it over against signature." },
    ],
  },
  "requete-conciliation-travail": {
    name: "Conciliation application (employment)",
    short: "Your application, ready to file with the conciliation authority, with exhibits in order.",
    intro: "Your employer still doesn't pay or disputes your rights despite your letters? Proceedings before the labour court generally begin with a conciliation attempt. We draft your application and explain how the hearing works.",
    included: [
      "Conciliation application with quantified claims",
      "List and ordering of exhibits",
      "Preparation sheet for the conciliation hearing",
    ],
    needs: "Your contract, correspondence with the employer and documents proving your claims.",
    note: "Employment disputes up to CHF 30,000 follow a simplified procedure free of court costs (art. 114 and 243 CPC). You file the application yourself: Thrax Legal does not represent you before the authorities.",
    faq: [
      { q: "Do I have to attend the hearing?", a: "Yes, personal attendance is generally mandatory. The preparation sheet helps you present your position calmly." },
      { q: "What if my case is complex?", a: "If your situation requires a lawyer, we tell you before you pay." },
    ],
  },
  "baisse-de-loyer": {
    name: "Rent reduction request",
    short: "Calculation of the reduction you're entitled to and a letter to your landlord, ready to send.",
    intro: "When the reference mortgage rate falls, your rent can fall too. We check your entitlement, calculate the reduction you can request and write the letter to your landlord or agency.",
    included: [
      "Check of the reference rate and your last rent adjustment",
      "Calculation of the reduction",
      "Rent reduction request, ready to send",
      "Next steps if the landlord refuses",
    ],
    needs: "Your lease and the last rent notification you received.",
    note: "The request is made in writing for the next termination date. The landlord has 30 days to reply; if they refuse or don't respond, you can apply to the conciliation authority within 30 days (art. 270a CO).",
    faq: [
      { q: "Can my landlord terminate my lease because I asked?", a: "No. Notice given because a tenant asserts their rights can be challenged (art. 271a CO)." },
      { q: "How much can I save?", a: "It depends on your last adjustment. The calculation shows the exact amount before you send anything." },
    ],
  },
  "contestation-loyer-initial": {
    name: "Challenging the initial rent",
    short: "Abusive starting rent? You have 30 days: analysis and an application ready to file.",
    intro: "You've just moved in and your rent is much higher than the previous tenant's? You may be able to challenge it. We assess your chances and draft the application to the conciliation authority.",
    included: [
      "Analysis of the conditions for a challenge",
      "Check of the official notification form",
      "Application to the conciliation authority, ready to file",
      "Explanation of the procedure and risks",
    ],
    needs: "Your lease, the official form (if any) and the date you received the keys.",
    note: "The deadline is 30 days from taking possession (art. 270 CO). In several cantons, the landlord must state the previous rent on an official form; if it is missing, this can also be invoked.",
    faq: [
      { q: "I'm past the deadline, what now?", a: "If the official form was missing, other options exist. Book a legal call to check." },
      { q: "Is it risky for my lease?", a: "The landlord cannot terminate for this reason during the proceedings and the following three years (art. 271a CO)." },
    ],
  },
  "defaut-logement": {
    name: "Defect in your home: rent reduction",
    short: "Mould, breakdown, noise, building works: defect notice and rent reduction request.",
    intro: "Mould, broken heating, leaks, a noisy building site: a lasting defect entitles you to repairs and a rent reduction. We write the defect notice and the reduction request, properly.",
    included: [
      "Assessment of the defect and the usual reduction",
      "Defect notice with a repair deadline",
      "Rent reduction request",
      "Explanation of rent deposit with the authority, if needed",
    ],
    needs: "Photos of the defect, the date you discovered it and your exchanges with the agency.",
    note: "Never simply stop paying rent: it is a ground for termination. Depositing the rent is only possible after a written notice and a reasonable deadline (art. 259g CO). The reduction applies from the moment the landlord knows of the defect (art. 259d CO).",
    faq: [
      { q: "How much can the rent drop?", a: "It depends on the severity and duration. We give you a range based on case law." },
      { q: "What if the agency doesn't react?", a: "The letter sets a deadline. After that, you can deposit the rent or apply to the conciliation authority." },
    ],
  },
  "garantie-de-loyer": {
    name: "Getting your rent deposit back",
    short: "Disputed repair costs, blocked deposit: we write your claim.",
    intro: "Your former agency is holding the deposit or charging you repair costs? We check what can really be claimed and write the challenge and the release request.",
    included: [
      "Analysis of the move-out report and the costs claimed",
      "Normal wear and tear versus damage you are liable for",
      "Challenge letter and deposit release request",
    ],
    needs: "Your lease, the move-in and move-out reports, and the agency's statement.",
    note: "Normal wear and tear is borne by the landlord (art. 267 CO). If the landlord has not asserted any claim in court or through debt enforcement within a year after the lease ends, you can ask the bank to release the deposit (art. 257e CO).",
    faq: [
      { q: "Can the agency keep the deposit indefinitely?", a: "No: after one year with no proceedings on their part, you can ask the bank directly." },
      { q: "I'm being charged for a full repaint, is that normal?", a: "Often not: the lifespan of the paint is taken into account. The letter disputes unjustified amounts." },
    ],
  },
  "resiliation-anticipee-bail": {
    name: "Early termination of your lease",
    short: "Leave before the end date without paying months of rent: letter and replacement tenant.",
    intro: "You need to move out before your lease ends? By presenting a replacement tenant, you can be released earlier. We write the termination letter and the presentation of the candidate.",
    included: [
      "Calculation of the ordinary end date and deadlines",
      "Compliant early termination letter",
      "Letter presenting the replacement tenant",
    ],
    needs: "Your lease and, if you already have them, the replacement tenant's details.",
    note: "The replacement tenant must be solvent, acceptable to the landlord and willing to take over the lease on the same terms (art. 264 CO). For the family home, both spouses must sign (art. 266m CO).",
    faq: [
      { q: "Can the landlord refuse my candidate?", a: "Only for valid reasons. Otherwise, you are released on the proposed date." },
      { q: "How many candidates do I need?", a: "One is enough if they meet the conditions. Two or three speed things up." },
    ],
  },
  "contestation-conge": {
    name: "Challenge a notice or extend the lease",
    short: "You have 30 days: application to the conciliation authority to cancel the notice or gain time.",
    intro: "You've received notice? You can challenge it if it is abusive, or request an extension if moving out causes serious hardship. We draft the application to the conciliation authority.",
    included: [
      "Check of the notice's formal validity",
      "Analysis of the reasons: challengeable or not",
      "Application for cancellation and/or extension, ready to file",
    ],
    needs: "The official notice form, the envelope or delivery slip, and your lease.",
    note: "The deadline is 30 days from receipt of the notice (art. 273 CO). Notice not given on the official form is void (art. 266l and 266o CO). Extensions can reach four years for a home (art. 272b CO).",
    faq: [
      { q: "When does the deadline start?", a: "From actual receipt or the last day of the post office collection period. Choose express if the date is close." },
      { q: "Will I gain time even if the notice is valid?", a: "Often yes: an extension can be granted in cases of hardship." },
    ],
  },
  "decompte-de-charges": {
    name: "Challenging the service charge statement",
    short: "Line-by-line check of your statement and a claim to the landlord.",
    intro: "Your heating and service charge statement has exploded? We check every item and write the claim to the agency, with a request to see the supporting documents.",
    included: [
      "Check of the items charged against the lease",
      "Identification of charges not agreed or excessive",
      "Claim letter and request for supporting documents",
    ],
    needs: "Your lease and the disputed statement.",
    note: "You only owe service charges expressly agreed in the lease (art. 257a CO), and you have the right to inspect the supporting documents (art. 257b CO).",
    faq: [
      { q: "Should I pay the balance in the meantime?", a: "We tell you which part to pay and which to dispute." },
      { q: "Can I challenge an old statement?", a: "Often yes, within limits. Mention the years concerned." },
    ],
  },
  "litige-de-voisinage": {
    name: "Neighbour dispute: formal letter",
    short: "Noise, plants, boundaries, nuisances: a clear, legally grounded letter.",
    intro: "Talking hasn't worked and the situation drags on? A formal, calm and legally grounded letter often solves the problem without going to court. We write it for you.",
    included: [
      "Analysis of the situation and the applicable rules",
      "Formal letter to the neighbour or the agency",
      "Tips for gathering evidence",
    ],
    needs: "A description of the problem, how long it has lasted and, if you have them, photos or a nuisance log.",
    note: "Everyone must refrain from any excessive impact on neighbours (art. 684 CC). Distances for trees and plants are set by cantonal law.",
    faq: [
      { q: "Won't the letter make things worse?", a: "It is firm but courteous, designed to open a solution rather than a conflict." },
      { q: "I'm a tenant, who should I write to?", a: "Often the agency, which must guarantee peaceful use of the home. We tell you who." },
    ],
  },
  "resiliation-de-contrat": {
    name: "Cancel a subscription or contract",
    short: "Gym, phone, insurance, subscription: the right deadline, form and date.",
    intro: "A subscription that renews automatically, an insurer refusing your cancellation, a gym that won't listen: we check your contract and write a cancellation that holds.",
    included: [
      "Check of the contract's cancellation terms",
      "Calculation of the possible end date",
      "Cancellation letter, ready to send",
    ],
    needs: "The contract or terms and conditions, and the date you want to stop.",
    note: "A late cancellation only takes effect at the next term. Insurance contracts can in principle be cancelled at the end of the third year, then every year (art. 35a ICA).",
    faq: [
      { q: "The provider refuses my cancellation?", a: "If it complies with the contract, it takes effect even without their agreement. The letter says so clearly." },
      { q: "Can I cancel for good cause?", a: "In some cases, yes. Describe your situation and we check." },
    ],
  },
  "garantie-achat-defectueux": {
    name: "Faulty purchase: claim under warranty",
    short: "Formal notice to the seller: repair, replacement or refund, according to your rights.",
    intro: "A faulty appliance, piece of furniture or vehicle, and the seller passes the buck? We check your warranty rights and write the formal notice.",
    included: [
      "Analysis of the legal and contractual warranty",
      "Choice of the best claim: repair, replacement, price reduction or cancellation",
      "Formal notice to the seller, ready to send",
    ],
    needs: "The invoice or receipt, the warranty terms and photos of the defect.",
    note: "The defect must be reported to the seller as soon as it is discovered (art. 201 CO). For new goods bought by a consumer, the two-year limit cannot be shortened (art. 210 CO).",
    faq: [
      { q: "The seller refers me to the manufacturer?", a: "The legal warranty binds the seller. The letter reminds them they remain your counterpart." },
      { q: "And for online purchases?", a: "The same rules apply for a seller based in Switzerland. For a foreign seller, we tell you the applicable law." },
    ],
  },
  "litige-artisan": {
    name: "Dispute with a tradesman or company",
    short: "Poor work, delays, quote exceeded: defect notice and formal notice.",
    intro: "Sloppy work, endless building site, invoice far above the quote: we analyse your contract and write the defect notice and formal notice to the tradesman.",
    included: [
      "Analysis of contract, quote and invoices",
      "Proper defect notice",
      "Formal notice: rework, deadline or price reduction",
    ],
    needs: "The quote or contract, invoices, photos and your exchanges with the company.",
    note: "Defects must be reported promptly after discovery. If an approximate estimate is excessively exceeded, you can ask for a reduction or withdraw from the contract (art. 375 CO).",
    faq: [
      { q: "Should I pay the invoice in the meantime?", a: "We tell you which part to pay and which to withhold, without putting you in the wrong." },
      { q: "What if SIA standard 118 applies?", a: "We take it into account: it has its own rules and deadlines for defects." },
    ],
  },
  "contester-une-facture": {
    name: "Dispute an invoice",
    short: "Unjustified or excessive invoice: a reasoned written dispute, ready to send.",
    intro: "An invoice for a service never ordered, an inflated amount, surprise fees: we write a clear dispute explaining why you don't owe that amount.",
    included: [
      "Analysis of the invoice and what was agreed",
      "Reasoned dispute letter",
      "Next steps in case of reminders or debt enforcement",
    ],
    needs: "The disputed invoice, the contract or offer, and your exchanges with the company.",
    note: "Paying \"for the sake of peace\" often amounts to acknowledging the debt. If you receive a payment order, you have 10 days to object (art. 74 DEBA).",
    faq: [
      { q: "Should I pay the undisputed part?", a: "Yes, it shows good faith. The letter states the acknowledged amount." },
      { q: "What if the company starts debt enforcement?", a: "Object within 10 days. See \"Unjustified debt enforcement\"." },
    ],
  },
  "relecture-contrat-particulier": {
    name: "Contract review before signing",
    short: "Leasing, loan, car purchase, building works: we review and flag the traps.",
    intro: "Before signing an important contract, have it reviewed. We flag unfavourable clauses, hidden costs and what you can negotiate.",
    included: [
      "Full review (up to 15 pages)",
      "List of risks and unusual clauses",
      "Suggested changes",
    ],
    needs: "The contract, the terms and conditions and any offer.",
    note: "For a lease or consumer credit, you can revoke your agreement within 14 days (art. 16 CCA).",
    faq: [
      { q: "The contract is over 15 pages?", a: "Order anyway: we confirm the exact price before starting." },
      { q: "How fast?", a: "Three working days, or 24 hours with the express option." },
    ],
  },
  "vol-annule-retarde": {
    name: "Cancelled or delayed flight: compensation",
    short: "Claim to the airline at a fixed price, with no commission on your compensation.",
    intro: "Cancellation, overbooking, long delay: you may be entitled to EUR 250 to 600 per passenger. We check your entitlement and write the claim, without taking a percentage.",
    included: [
      "Check of entitlement and amount",
      "Claim to the airline, ready to send",
      "Next steps if refused",
    ],
    needs: "The booking, boarding pass and what the airline told you.",
    note: "The EU air passenger rights regulation also applies in Switzerland, notably to flights departing from Swiss airports. Extraordinary circumstances (weather, air traffic control strike) can rule out compensation.",
    faq: [
      { q: "Why not a claims platform?", a: "They often keep 25 to 35% of the compensation. Here you pay a fixed price and keep the rest." },
      { q: "For several passengers?", a: "One order covers everyone on the same booking." },
    ],
  },
  "refus-assurance": {
    name: "Insurance refusal: claim",
    short: "Household, travel, vehicle, legal protection: a reasoned claim to the insurer.",
    intro: "Your insurer refuses to pay or only reimburses part? We analyse your policy and the decision, then write a reasoned claim.",
    included: [
      "Analysis of the policy, general terms and refusal",
      "Legal and contractual arguments",
      "Claim to the insurer, ready to send",
      "Next steps: ombudsman, proceedings",
    ],
    needs: "The policy, general terms, refusal letter and documents about the claim.",
    note: "Claims under an insurance contract generally expire after five years (art. 46 ICA). The private insurance ombudsman can help free of charge.",
    faq: [
      { q: "And for a health insurer (basic insurance)?", a: "That's social insurance: see \"Objection to a social insurance decision\"." },
      { q: "The insurer relies on an exclusion?", a: "Not necessarily the end: exclusions must be clear and, in case of doubt, are interpreted in favour of the insured." },
    ],
  },
  "poursuite-injustifiee": {
    name: "Unjustified debt enforcement: objection and removal",
    short: "Unjustified payment order: objection, then a request to stop disclosure in the register.",
    intro: "You've received a payment order for a debt you dispute? We explain how to object and then write the non-disclosure request, so the enforcement no longer appears on your extract.",
    included: [
      "Check of the payment order and deadlines",
      "Instructions for the objection",
      "Non-disclosure request to the debt enforcement office, at the right time",
    ],
    needs: "The payment order (photo or PDF) and what you know about the claim.",
    note: "The objection must be made within 10 days of service (art. 74 DEBA). Three months later, you can ask that the enforcement no longer be disclosed to third parties if the creditor has not acted (art. 8a DEBA).",
    faq: [
      { q: "Does objecting cost anything?", a: "No, the objection is free and needs no reasons." },
      { q: "Does the enforcement really disappear?", a: "It is no longer disclosed to third parties, such as a future landlord, if the creditor has not pursued the procedure." },
    ],
  },
  "recuperer-argent-prete": {
    name: "Recover money lent or owed",
    short: "Formal notice and a debt enforcement request ready to file, for a loan or private debt.",
    intro: "You lent money to someone close, sold something without being paid or advanced costs? We write the formal notice and prepare the debt enforcement request if nothing happens.",
    included: [
      "Analysis of the evidence of the claim",
      "Formal notice with payment deadline",
      "Debt enforcement request prepared, ready to file",
    ],
    needs: "Evidence of the loan or debt: messages, transfers, acknowledgement of debt.",
    note: "A loan with no due date must be repaid within six weeks of the first demand (art. 318 CO). A signed acknowledgement of debt makes the next steps much easier (art. 82 DEBA).",
    faq: [
      { q: "I have no written contract, is it possible?", a: "Yes: messages, transfers and witnesses can prove the loan. We assess the strength of your evidence." },
      { q: "What if the debtor objects?", a: "You will need a removal of objection or a court action. We explain the next steps and costs." },
    ],
  },
  "reclamation-taxation-impots": {
    name: "Objection to a tax assessment",
    short: "Deduction refused, income misjudged: a reasoned objection within 30 days.",
    intro: "Your tax assessment doesn't match your return? Deduction refused, income estimated ex officio, calculation error: we write a reasoned objection.",
    included: [
      "Comparison between your return and the assessment",
      "Arguments and documents to attach",
      "Objection ready to send",
    ],
    needs: "The assessment, your tax return and the relevant supporting documents.",
    note: "The objection must be filed within 30 days of notification, in writing and with reasons (art. 132 DFTA for federal tax, similar rules in the cantons).",
    faq: [
      { q: "Can the 30-day deadline be extended?", a: "No, it is set by law. If the date is close, choose express." },
      { q: "Can the tax go up after an objection?", a: "The authority reviews the whole assessment: we check that risk before filing." },
    ],
  },
  "opposition-assurance-sociale": {
    name: "Objection to a social insurance decision",
    short: "Unemployment, AHV/AVS, health insurance, accident: a reasoned objection within 30 days.",
    intro: "Suspension days from unemployment insurance, benefits refused by the health insurer, a pension calculated too low: we analyse the decision and write your objection.",
    included: [
      "Analysis of the decision and the applicable rules",
      "Arguments and documents to attach",
      "Objection ready to send",
    ],
    needs: "The decision, the correspondence and useful documents (certificates, contracts, attestations).",
    note: "The objection must be filed within 30 days (art. 52 ATSG). For disability insurance the procedure differs: you comment on the preliminary decision, then appeal.",
    faq: [
      { q: "Is the objection free?", a: "Yes, the objection procedure is generally free." },
      { q: "What if it is rejected?", a: "An appeal to the cantonal court is possible within 30 days. We tell you whether a lawyer is advisable." },
    ],
  },
  testament: {
    name: "Will: guided drafting",
    short: "A tailor-made will under the new inheritance law, to copy out by hand.",
    intro: "Favour your spouse, protect your partner, leave a specific asset: we help you draft a clear will under the inheritance law in force since 2023, which you copy out by hand.",
    included: [
      "Calculation of compulsory shares and the freely disposable portion",
      "Text of the will tailored to your wishes",
      "Instructions to copy, date, sign and keep it",
    ],
    needs: "Your family situation, your main assets and what you want to leave to whom.",
    note: "A handwritten will must be entirely written by hand, dated and signed (art. 505 CC). Since 2023, parents no longer have a compulsory share and that of descendants is half of their legal share.",
    faq: [
      { q: "Do I need a notary?", a: "Not for a handwritten will. A notarised will remains advisable for complex situations." },
      { q: "Does my unmarried partner inherit?", a: "No, unless there is a will. That is exactly what the will can provide." },
    ],
  },
  "mandat-pour-cause-d-inaptitude": {
    name: "Advance care directive (incapacity mandate)",
    short: "Choose who will decide for you if you no longer can: assets, health, admin.",
    intro: "Accident, illness: if you can no longer manage your affairs, the protection authority appoints someone. With an incapacity mandate, you choose. We draft it with you.",
    included: [
      "Choice of areas: personal care, assets, representation",
      "Mandate text tailored to your situation",
      "Instructions on form and registration",
    ],
    needs: "The person or people chosen and what you want to entrust to them.",
    note: "The mandate must be entirely handwritten, dated and signed, or notarised (art. 361 CC). Its existence can be registered with the civil registry.",
    faq: [
      { q: "Can't my spouse already represent me?", a: "Only for everyday matters (art. 374 CC). The mandate goes further." },
      { q: "Can I change it?", a: "Yes, at any time while you have capacity." },
    ],
  },
  "directives-anticipees": {
    name: "Living will (patient decree)",
    short: "Your medical wishes, clear and valid, and the person who will enforce them.",
    intro: "Which treatments to accept or refuse if you can no longer express yourself? A living will states it clearly and names the person who will speak for you.",
    included: [
      "Guided questionnaire on your wishes",
      "Precisely worded directives",
      "Appointment of a representative for medical decisions",
    ],
    needs: "Your wishes and the trusted person you want to appoint.",
    note: "A living will must be in writing, dated and signed (art. 371 CC). It can be noted on your health insurance card.",
    faq: [
      { q: "Must the doctor follow it?", a: "Yes, unless it breaches the law or no longer reflects your presumed wishes (art. 372 CC)." },
      { q: "Do I need a notary?", a: "No, written, dated and signed is enough." },
    ],
  },
  "convention-de-concubinage": {
    name: "Cohabitation agreement",
    short: "Home, shared costs, assets, separation: everything set out in black and white.",
    intro: "Unmarried couples have almost no legal rules protecting them. A cohabitation agreement covers the home, expenses, things bought together and what happens if you separate.",
    included: [
      "Analysis of your shared situation",
      "Tailor-made agreement: home, costs, assets, separation",
      "Recommendations: will, pension, insurance",
    ],
    needs: "Your situation: home, income, shared assets, any children.",
    note: "In cohabitation, neither partner inherits without a will, and the shared home is not protected like that of spouses.",
    faq: [
      { q: "Is the agreement valid without a notary?", a: "Yes, a written agreement signed by both partners is enough." },
      { q: "What if we have children?", a: "We include the useful points and tell you what must be settled with the authority (parental authority, maintenance)." },
    ],
  },
  "separation-divorce-amiable": {
    name: "Amicable divorce without minor children",
    short: "Agreement and joint petition, for couples without minor children who agree on the essentials.",
    intro: "You agree on the essentials, have no minor children and want to avoid lengthy proceedings? We draft, neutrally and for both of you, the divorce agreement and the joint petition you file with the court.",
    included: [
      "Scoping meeting with both spouses",
      "Agreement: home, maintenance, assets, sharing of occupational pension",
      "Joint divorce petition ready to file, with the list of documents",
    ],
    needs: "Income, each spouse's pension statements (2nd pillar) and the list of assets.",
    note: "Divorce on joint petition does not require a lawyer: the spouses file the petition and agreement themselves (art. 111 CC). The judge checks that the agreement is clear, complete and fair. We act neutrally for both spouses, and only if both agree.",
    faq: [
      { q: "What if we have minor children?", a: "We don't take these cases: parental authority, custody and maintenance call for a family mediator or a lawyer. We point you in the right direction." },
      { q: "Why \"from CHF 590\"?", a: "The price applies to a simple situation with no real estate or business. It is confirmed in writing after our first exchange, before any payment." },
    ],
  },
  "question-juridique": {
    name: "Legal question: written answer",
    short: "One precise question, a clear written answer with the relevant legal provisions.",
    intro: "You have a precise question and want a reliable answer without an appointment? Ask it: you get a clear written answer with the next steps.",
    included: [
      "Legal research on your question",
      "Clear written answer with legal bases",
      "Recommended next step",
    ],
    needs: "Your question and the context in a few lines.",
    note: "A quick question covers one precise point. If your situation needs a document or a full analysis, we propose the right service before starting.",
    faq: [
      { q: "What about a follow-up question?", a: "One clarification on the answer received is included." },
      { q: "Which areas?", a: "Employment, tenancy, consumer, contracts, debt enforcement, simple family matters. For criminal law, we refer you to a lawyer." },
    ],
  },
  "appel-juridique": {
    name: "20-minute legal call",
    short: "You explain your situation, we tell you what to do and by when.",
    intro: "Prefer to talk it through? Book a 20-minute call: you explain your situation and we tell you what you can do, the deadlines, and what to avoid.",
    included: [
      "20-minute phone or video call",
      "Preparation based on your written description",
      "Written summary of the next steps",
    ],
    needs: "A description of your situation and your availability.",
    note: "If you then order a related service within 30 days, the price of the call is deducted.",
    faq: [
      { q: "When does the call take place?", a: "We offer slots within two working days." },
      { q: "What if 20 minutes isn't enough?", a: "The written summary names the right service and its fixed price." },
    ],
  },
  "lettre-juridique-sur-mesure": {
    name: "Tailor-made legal letter",
    short: "A formal letter adapted to your situation, legally grounded and ready to send.",
    intro: "Your situation doesn't fit any box? We write the formal letter you need: complaint, dispute, request, formal notice.",
    included: [
      "Analysis of your situation",
      "Legally grounded letter, ready to send",
      "One round of revisions",
    ],
    needs: "Your situation, the recipient and the relevant documents.",
    note: "A well-written letter sets a deadline, cites the right rules and leaves a written record that is useful in any proceedings.",
    faq: [
      { q: "Is the letter signed by Thrax Legal?", a: "No, it is written in your name and you send it yourself." },
      { q: "What if the situation is more complex?", a: "We tell you before starting and quote the right price." },
    ],
  },
  "mise-en-demeure": {
    name: "Formal notice",
    short: "Client, supplier, tenant, partner: a formal letter with deadline and announced consequences, the last warning before proceedings.",
    intro: "Someone is not honouring their commitments to your business? A client who doesn't pay, a supplier who doesn't deliver, a tenant in arrears, a partner who breaks their word: a formal notice with a deadline and announced next steps often unblocks the situation.",
    included: [
      "Check of your rights and documents",
      "Default interest calculation for a sum of money",
      "Formal notice on your letterhead, ready to send",
    ],
    needs: "The contract, order or invoice concerned, and your exchanges with the other party.",
    note: "For a sum of money, default interest of 5% per year is due from default (art. 104 CO). For an unperformed obligation, a formal notice with an additional deadline gives the right to waive performance or withdraw from the contract (art. 107 CO).",
    faq: [
      { q: "Should I send it by registered mail?", a: "Recommended to prove receipt. Sending it by email in parallel often speeds up the response." },
      { q: "What if the other party still doesn't react?", a: "For an invoice, move on to full debt collection. Otherwise, we tell you the next steps: withdrawal, damages or proceedings." },
    ],
  },
  "recouvrement-facture-impayee": {
    name: "Unpaid invoice collection",
    short: "Formal notice, prepared debt enforcement request, follow-up on objections: we handle it all.",
    intro: "An invoice unpaid for weeks? We take care of the whole amicable process and the preparation of debt enforcement, up to the request to set aside an objection if the debtor objects.",
    included: [
      "Formal notice with interest",
      "Debt enforcement request prepared, ready to file",
      "Analysis of any objection and next steps",
      "Tips to preserve the client relationship where possible",
    ],
    needs: "The invoice, the contract or order, your reminders and the debtor's details.",
    note: "Claims generally expire after ten years, but after five years for many everyday services (art. 127 and 128 CO). You file the request yourself: professional representation before debt enforcement offices is regulated by the cantons.",
    faq: [
      { q: "Why not a collection agency?", a: "They take a percentage or charge fees to the debtor, sometimes contested. Here the price is fixed and the client relationship is preserved." },
      { q: "Several invoices from the same client?", a: "One service covers all invoices of the same debtor." },
    ],
  },
  "requete-de-mainlevee": {
    name: "Application to set aside an objection",
    short: "After an objection: application ready to file, with exhibits in order.",
    intro: "Your debtor has objected to the payment order? With an acknowledgement of debt or a judgment, you can continue enforcement by having the objection set aside. We draft the application.",
    included: [
      "Check of the title: acknowledgement of debt or judgment",
      "Application for provisional or definitive removal, ready to file",
      "List of exhibits",
    ],
    needs: "The payment order with the objection, the signed contract or acknowledgement of debt, and the invoices.",
    note: "A signed acknowledgement of debt allows provisional removal (art. 82 DEBA), an enforceable judgment definitive removal (art. 80 DEBA). Without a title, you must sue for recognition of the debt.",
    faq: [
      { q: "Is a signed contract enough?", a: "Often yes, if the service was provided and the amount clearly follows from the contract." },
      { q: "Who files the application?", a: "You, with the competent court. We tell you which one and how." },
    ],
  },
  "litige-commercial": {
    name: "Commercial dispute: analysis and letter",
    short: "Client, supplier or partner: your position analysed and defended in writing.",
    intro: "Non-conforming delivery, disputed service, breach of contract: we analyse the situation and write the letter that defends your position and opens the way to a solution.",
    included: [
      "Analysis of the contract and exchanges",
      "Assessment of your position and the risks",
      "Formal letter to the other party",
    ],
    needs: "The contract, invoices and key correspondence.",
    note: "Written records matter: a precise letter sent early strengthens your position in any proceedings.",
    faq: [
      { q: "What if it goes to court?", a: "We refer you to a lawyer and hand over a clean file." },
      { q: "Can you negotiate for us?", a: "We prepare your letters and arguments; you remain the contact." },
    ],
  },
  "cgv-sur-mesure": {
    name: "Tailor-made T&Cs",
    short: "Terms and conditions written for your business: payment, liability, warranty, jurisdiction.",
    intro: "T&Cs copied from a competitor don't protect you. We draft terms adapted to your business, your customers (businesses or consumers) and how you sell.",
    included: [
      "Questionnaire on your business and risks",
      "Complete T&Cs: order, price, payment, default, warranty, liability, jurisdiction",
      "Advice on incorporating them validly (website, quotes, invoices)",
      "One round of revisions",
    ],
    needs: "A description of your business and your current documents (quote, invoice, existing T&Cs).",
    note: "T&Cs only apply if the customer could read them before contracting. Towards consumers, unbalanced clauses are unfair (art. 8 UCA).",
    faq: [
      { q: "Does the online shop need separate T&Cs?", a: "Often yes, or a dedicated chapter. We include it if you sell online." },
      { q: "In which languages?", a: "In French by default. A translation can be added on quote." },
    ],
  },
  "contrat-commercial-sur-mesure": {
    name: "Tailor-made commercial contract",
    short: "Services, subcontracting, distribution, partnership: a contract written for your situation.",
    intro: "An important deal deserves a real contract. We draft a contract adapted to your business relationship, with the clauses that protect your interests.",
    included: [
      "Scoping of the deal and the risks",
      "Complete contract: purpose, price, deadlines, liability, termination, jurisdiction",
      "One round of revisions",
    ],
    needs: "The points agreed with your partner and your existing documents.",
    note: "Most commercial contracts require no particular form, but a clear written text prevents most disputes.",
    faq: [
      { q: "What if the other party proposes its own contract?", a: "Choose the commercial contract review instead." },
      { q: "Contract in English?", a: "Possible, price confirmed before starting." },
    ],
  },
  "relecture-contrat-commercial": {
    name: "Commercial contract review",
    short: "Risks flagged and corrections proposed, before you sign (up to 20 pages).",
    intro: "A client or supplier sends you their contract? We review it, flag dangerous clauses and propose corrections to negotiate.",
    included: [
      "Full review (up to 20 pages)",
      "Risks ranked by priority",
      "Proposed corrections in tracked changes",
    ],
    needs: "The contract (Word preferred) and the context of the relationship.",
    note: "Liability, penalty, term and jurisdiction clauses are the ones that cost the most when things go wrong.",
    faq: [
      { q: "More than 20 pages?", a: "The price is confirmed before starting, per block of 20 pages." },
      { q: "Contract in English?", a: "Yes, review in English is possible." },
    ],
  },
  "accord-de-confidentialite": {
    name: "Non-disclosure agreement (NDA)",
    short: "One-way or mutual, adapted to your project, with a deterrent contractual penalty.",
    intro: "Before presenting a project, know-how or figures, protect them. We draft an NDA adapted to your situation.",
    included: [
      "Choice between one-way and mutual agreement",
      "Precise definition of the protected information",
      "Appropriate contractual penalty and duration",
    ],
    needs: "The parties, the project and the information to protect.",
    note: "A contractual penalty (art. 160 ff. CO) avoids having to prove the exact amount of damage in case of breach.",
    faq: [
      { q: "Isn't a free template enough?", a: "Often it poorly protects what matters to you or provides an unenforceable penalty." },
      { q: "In English?", a: "Yes, at no extra cost for a standard NDA." },
    ],
  },
  "contrat-de-mandat-independant": {
    name: "Freelance services agreement",
    short: "Assignment, fees, liability, intellectual property: a solid freelance contract.",
    intro: "Whether you are a freelancer or hiring one, a clear contract avoids misunderstandings and the risk of being requalified as employment.",
    included: [
      "Mandate or contract for work depending on the assignment",
      "Fee, liability and intellectual property clauses",
      "Points to watch regarding self-employed status",
    ],
    needs: "The assignment, duration, fees and parties.",
    note: "Self-employed status for AHV/AVS purposes depends on the reality of the collaboration, not just the contract. A mandate can be terminated at any time by either party (art. 404 CO).",
    faq: [
      { q: "Mandate or contract for work?", a: "It depends on the result promised. We choose the right qualification and explain it." },
      { q: "For several clients?", a: "We can draft a reusable template; mention it in your request." },
    ],
  },
  "contrat-de-travail-sur-mesure": {
    name: "Tailor-made employment contract",
    short: "Adapted to the role and collective agreement, with the clauses that protect the company.",
    intro: "A well-drafted employment contract prevents most disputes: working time, overtime, holidays, non-compete, confidentiality. We draft it for the role concerned.",
    included: [
      "Check of the applicable collective agreement",
      "Complete contract adapted to the role",
      "Essential written clauses: overtime, non-compete, confidentiality",
      "One round of revisions",
    ],
    needs: "The role, workload, salary, start date and your internal practices.",
    note: "Some clauses are only valid in writing, such as excluding overtime compensation (art. 321c CO) or a non-compete (art. 340 CO). An extended collective agreement applies even without membership.",
    faq: [
      { q: "A template for several employees?", a: "Yes, we can draft a template for several similar roles; mention it in your request." },
      { q: "And for an apprentice?", a: "Apprenticeship contracts follow an official cantonal form; we point you in the right direction." },
    ],
  },
  "certificat-de-travail-employeur": {
    name: "Work reference drafting",
    short: "Complete, accurate and benevolent, with no wording that can backfire on you.",
    intro: "Writing a work reference takes time and has pitfalls: too flattering, it creates liability; too harsh, it invites a dispute. We draft it from your input.",
    included: [
      "Quick questionnaire about the employee",
      "Full reference or simple confirmation of employment",
      "Wording in line with practice",
    ],
    needs: "The role, dates, main tasks and your assessment of work and conduct.",
    note: "The reference must be complete, accurate and benevolent (art. 330a CO). A misleadingly glowing reference can make you liable towards a future employer.",
    faq: [
      { q: "Interim reference?", a: "Yes, same price." },
      { q: "How fast?", a: "Two working days, or 24 hours with express." },
    ],
  },
  "licenciement-employeur": {
    name: "Safe dismissal",
    short: "Notice checked, protection periods reviewed, compliant dismissal letter.",
    intro: "A poorly prepared dismissal can be void or abusive. We check deadlines and protection periods, then draft the dismissal letter and written reasons.",
    included: [
      "Check of the notice period and end date",
      "Review of protection periods",
      "Dismissal letter and written reasons",
      "Points to watch: holiday balance, reference, insurance",
    ],
    needs: "The employment contract, the employee's situation (absences, pregnancy…) and the reason.",
    note: "Notice given during a protection period (illness, accident, pregnancy, service) is void (art. 336c CO). An abusive dismissal can cost up to six months' salary (art. 336a CO).",
    faq: [
      { q: "And a summary dismissal?", a: "It requires valid grounds (art. 337 CO), often preceded by a warning. We assess the risk first." },
      { q: "Is a prior meeting required?", a: "Generally not mandatory, but recommended. We give you an outline." },
    ],
  },
  "avertissement-employe": {
    name: "Written warning",
    short: "Facts, expectations, consequences: a warning that holds up in a dispute.",
    intro: "Repeated lateness, inappropriate behaviour, instructions ignored: a precise, proportionate written warning protects the company if the situation leads to dismissal.",
    included: [
      "Factual description of the shortcomings",
      "Clear expectations and announced consequences",
      "Warning ready to hand over",
    ],
    needs: "The facts, dates and any previous warnings.",
    note: "For moderately serious misconduct, a summary dismissal generally requires a prior warning that went unheeded.",
    faq: [
      { q: "Must the employee sign?", a: "A signature acknowledging receipt is useful; otherwise hand it over in front of a witness." },
      { q: "How long does it remain valid?", a: "There is no fixed period; the older it is, the less weight it carries." },
    ],
  },
  "reglement-du-personnel": {
    name: "Staff regulations",
    short: "Working hours, holidays, expenses, remote work, data: clear rules for the whole team.",
    intro: "From just a few employees, staff regulations save you renegotiating every rule. We draft them for your company, consistent with your contracts and collective agreement.",
    included: [
      "Questionnaire on your practices",
      "Complete regulations: working time, absences, expenses, remote work, IT, data",
      "Advice on implementation and communication",
      "One round of revisions",
    ],
    needs: "Your standard contracts, current practices and the applicable collective agreement.",
    note: "The regulations must be made known to employees and incorporated into contracts to be binding.",
    faq: [
      { q: "From how many employees?", a: "From two or three, they save time and avoid unequal treatment." },
      { q: "Can they be changed later?", a: "Yes, respecting the notice periods for changes to working conditions." },
    ],
  },
  "pack-conformite-nlpd": {
    name: "FADP compliance pack",
    short: "Privacy policy, record of processing activities, clauses and notices: your compliance.",
    intro: "Since 1 September 2023, the new Data Protection Act applies to all companies. We inventory your processing and draft the essential documents.",
    included: [
      "Guided inventory of your processing and processors",
      "Privacy policy for the website and clients",
      "Record of processing activities",
      "Clauses for your contracts and processors",
    ],
    needs: "Your website, your tools (CRM, newsletter, accounting, cloud) and your data types.",
    note: "You must inform people when collecting their data (art. 19 FADP). Intentional breaches of certain duties expose those responsible to fines of up to CHF 250,000 (art. 60 FADP).",
    faq: [
      { q: "Is the record mandatory for an SME?", a: "Not always below 250 employees, but it is the best proof of compliance and is often requested by clients." },
      { q: "And the GDPR?", a: "If it applies to you, we include it in the documents." },
    ],
  },
  "politique-de-confidentialite": {
    name: "Website privacy policy",
    short: "FADP-compliant, adapted to your tools: forms, analytics, newsletter.",
    intro: "Your website collects data via a form, analytics or a newsletter? It needs an accurate privacy policy adapted to the tools you actually use.",
    included: [
      "Inventory of the website's tools",
      "Complete privacy policy",
      "Website legal notice",
    ],
    needs: "The website address and the list of your tools (hosting, analytics, forms, newsletter).",
    note: "A generic policy that doesn't match your actual processing does not fulfil the duty to inform (art. 19 FADP).",
    faq: [
      { q: "What about cookies?", a: "We tell you whether a banner is needed based on your tools." },
      { q: "In several languages?", a: "Translation possible, price confirmed before starting." },
    ],
  },
  "relecture-bail-commercial": {
    name: "Commercial lease review",
    short: "Rent, indexation, term, restoration: the points to negotiate before signing.",
    intro: "A commercial lease often binds you for five years or more. We review it and flag unfavourable clauses and points to negotiate.",
    included: [
      "Full review of the lease and annexes",
      "Points to negotiate: rent, indexation, term, options, works, restoration",
      "List of questions to ask the landlord",
    ],
    needs: "The draft lease, the annexes and the condition report if there is one.",
    note: "The initial rent of commercial premises can also be challenged within 30 days (art. 270 CO). The three-month deposit cap only applies to homes.",
    faq: [
      { q: "What if I've already signed?", a: "The review tells you your rights and the deadlines to watch." },
      { q: "Taking over a business?", a: "Mention it: lease transfer and key money are analysed." },
    ],
  },
  "convention-d-actionnaires": {
    name: "Shareholders' or partners' agreement",
    short: "Governance, exit, pre-emption, non-compete: the rules between partners.",
    intro: "The articles don't cover everything. A shareholders' or partners' agreement organises decisions, the arrival and departure of a partner, and protects everyone in case of disagreement.",
    included: [
      "Scoping meeting",
      "Complete agreement: governance, transfers, pre-emption, exit, non-compete",
      "Contractual penalties and deadlock mechanisms",
      "One round of revisions",
    ],
    needs: "The articles of association, the capital split and the sensitive points between partners.",
    note: "The agreement binds the partners among themselves, not the company: contractual penalties ensure it is respected.",
    faq: [
      { q: "More than three partners?", a: "The price is confirmed before starting." },
      { q: "Is a notary needed?", a: "Not for the agreement itself; amending the articles of an AG/SA or GmbH/Sàrl requires a notarial deed." },
    ],
  },
  "statuts-d-association": {
    name: "Association articles",
    short: "Compliant with the Civil Code, adapted to your project: purpose, bodies, members, finances.",
    intro: "Sports club, cultural association, neighbourhood project: we draft clear articles compliant with the Civil Code and the minutes of the founding meeting.",
    included: [
      "Complete articles",
      "Minutes of the founding meeting",
      "Guidance on commercial register entry if needed",
    ],
    needs: "The association's purpose, the founding members and the desired organisation.",
    note: "The articles must be in writing and state the association's purpose, resources and organisation (art. 60 CC).",
    faq: [
      { q: "Is commercial register entry mandatory?", a: "Only in some cases (commercial activity, mandatory audit). We tell you." },
      { q: "Can the articles be changed later?", a: "Yes, by decision of the general meeting." },
    ],
  },
};

export const SERVICE_TEXT_EN = { services, categories };
