import type { CategoryId } from "@/lib/services/catalog";
import type { CategoryText, ServiceText } from "./types";

const categories: Record<CategoryId, CategoryText> = {
  travail: { name: "Lavoro", lead: "I vostri diritti nei confronti del datore di lavoro" },
  logement: { name: "Abitazione & vicinato", lead: "Pigione, difetti, garanzia, disdetta" },
  consommation: { name: "Acquisti, contratti & viaggi", lead: "Garanzia, disdetta, rimborso" },
  argent: { name: "Denaro & esecuzioni", lead: "Recuperare il vostro denaro, contestare un'esecuzione" },
  administration: { name: "Imposte & assicurazioni sociali", lead: "Decisioni da contestare entro 30 giorni" },
  famille: { name: "Famiglia & futuro", lead: "Proteggere i vostri cari e le vostre volontà" },
  "sur-mesure": { name: "Su misura", lead: "La vostra situazione non è nell'elenco" },
  recouvrement: { name: "Incasso & controversie", lead: "Farsi pagare dai clienti, difendere la propria posizione" },
  contrats: { name: "Contratti & CG", lead: "Contratti che vi proteggono davvero" },
  employeurs: { name: "Datori di lavoro", lead: "Assumere, gestire e separarsi senza rischi" },
  conformite: { name: "Conformità & società", lead: "nLPD, locazione commerciale, soci" },
};

const services: Record<string, ServiceText> = {
  "analyse-certificat-de-travail": {
    name: "Analisi del vostro certificato di lavoro",
    short: "Leggiamo il certificato come lo leggerebbe un selezionatore e vi diciamo francamente se vi aiuta o vi frena.",
    intro: "Un certificato di lavoro può sembrare positivo e contenere comunque formule in codice, omissioni o sfumature che frenano le vostre candidature. Lo analizziamo frase per frase e vi diciamo cosa dice davvero ai selezionatori.",
    included: [
      "Lettura di ogni frase, formule in codice e omissioni comprese",
      "Valutazione globale: molto buono, buono, medio o da correggere",
      "Elenco dei punti che avete diritto di far modificare",
      "Raccomandazione chiara: tenerlo così o chiedere una rettifica",
    ],
    needs: "Il certificato di lavoro (foto leggibile o PDF) e, se possibile, il mansionario.",
    note: "Il datore di lavoro deve rilasciarvi un certificato completo, veritiero e formulato con benevolenza, che indichi natura e durata del rapporto, qualità del lavoro e condotta (art. 330a CO). Potete chiedere un certificato intermedio in qualsiasi momento.",
    faq: [
      { q: "Che cos'è una formula in codice?", a: "Una frase apparentemente positiva che segnala una debolezza ai selezionatori, ad esempio una soddisfazione «nel complesso». L'analisi le individua e le spiega." },
      { q: "E se il certificato va corretto?", a: "Potete passare alla richiesta di rettifica: il prezzo dell'analisi viene dedotto se ordinate entro 30 giorni." },
    ],
  },
  "rectification-certificat-de-travail": {
    name: "Far correggere il certificato di lavoro",
    short: "Troviamo le frasi che vi penalizzano e scriviamo al datore di lavoro per ottenere una nuova versione.",
    intro: "Il vostro certificato contiene formule vaghe, omissioni o frasi che vi penalizzano? Lo analizziamo frase per frase e redigiamo la lettera al datore di lavoro con le riformulazioni a cui avete diritto.",
    included: [
      "Analisi completa del certificato, formule in codice e omissioni comprese",
      "Proposta di testo corretto, frase per frase",
      "Lettera di richiesta di rettifica, pronta da inviare",
      "Come procedere se il datore di lavoro rifiuta",
    ],
    needs: "Il certificato di lavoro, il contratto se lo avete e due righe su ciò che non vi convince.",
    note: "Il certificato deve essere completo, veritiero e benevolo (art. 330a CO). In caso di rifiuto è possibile un'azione di rettifica: per le controversie di lavoro fino a CHF 30'000 la procedura è gratuita (art. 114 CPC).",
    faq: [
      { q: "Il datore di lavoro saprà che mi aiutate?", a: "No. La lettera è redatta a vostro nome e la inviate voi." },
      { q: "Il datore di lavoro può rifiutare?", a: "Non può rifiutarsi di correggere un'indicazione inesatta o incompleta. Se rifiuta senza motivo, la lettera prepara il seguito e vi spieghiamo le opzioni." },
    ],
  },
  "licenciement-opposition": {
    name: "Contestare un licenziamento",
    short: "Verifichiamo se termini e periodi di protezione sono stati rispettati, poi redigiamo la vostra opposizione.",
    intro: "Siete stati licenziati e qualcosa non vi convince? Verifichiamo se la disdetta rispetta i termini, se cade in un periodo di protezione e se può essere abusiva, poi redigiamo la vostra opposizione scritta.",
    included: [
      "Verifica del termine di disdetta e della data di fine",
      "Controllo dei periodi di protezione: malattia, infortunio, gravidanza, servizio militare",
      "Analisi del motivo: abusivo o no",
      "Lettera di opposizione e richiesta di motivazione scritta, pronte da inviare",
    ],
    needs: "La lettera di licenziamento, il contratto di lavoro e le date importanti (malattia, colloqui…).",
    note: "Per chiedere un'indennità per disdetta abusiva dovete fare opposizione per scritto prima della fine del termine di disdetta, poi agire entro 180 giorni dalla fine del rapporto (art. 336b CO). Una disdetta data durante un periodo di protezione è nulla (art. 336c CO).",
    faq: [
      { q: "Quanto tempo ho?", a: "L'opposizione deve giungere al datore di lavoro prima della fine del termine di disdetta. Scegliete l'opzione express se la data si avvicina." },
      { q: "Riavrò il mio posto?", a: "Nel diritto svizzero una disdetta abusiva resta valida: dà diritto a un'indennità di al massimo sei mesi di salario. Una disdetta data durante un periodo di protezione è invece nulla." },
    ],
  },
  "relecture-contrat-de-travail": {
    name: "Verificare un contratto di lavoro prima di firmare",
    short: "Leggiamo tutto il contratto e vi segnaliamo cosa vale la pena negoziare, come il periodo di prova o un divieto di concorrenza.",
    intro: "Vi è stato proposto un contratto e volete sapere cosa firmate? Lo rileggiamo e vi segnaliamo le clausole sfavorevoli, insolite o nulle, con ciò che potete negoziare.",
    included: [
      "Rilettura completa del contratto (fino a 15 pagine)",
      "Punti a rischio: prova, ore supplementari, divieto di concorrenza, mobilità, vacanze",
      "Confronto con il contratto collettivo applicabile, se esiste",
      "Proposte di modifica da chiedere prima della firma",
    ],
    needs: "Il contratto proposto e, se l'avete, l'offerta o l'annuncio.",
    note: "Il periodo di prova non può superare tre mesi (art. 335b CO). Il divieto di concorrenza è valido solo se scritto e se avete accesso alla clientela o a segreti d'affari (art. 340 CO).",
    faq: [
      { q: "Posso negoziare il contratto?", a: "Sì, prima di firmare. Vi indichiamo i punti prioritari e una formulazione cortese per affrontarli." },
      { q: "E se ho già firmato?", a: "La verifica resta utile: alcune clausole sono nulle anche se firmate. Vi diciamo quali." },
    ],
  },
  "salaire-impaye": {
    name: "Recuperare salario, ore supplementari o vacanze non pagati",
    short: "Calcoliamo quanto vi deve il datore di lavoro e gli inviamo una diffida con un termine per pagare.",
    intro: "Salario in ritardo, ore supplementari mai pagate, saldo vacanze ignorato alla fine del contratto: calcoliamo esattamente quanto vi spetta e redigiamo la diffida al datore di lavoro.",
    included: [
      "Calcolo dettagliato (salario, ore, vacanze, tredicesima)",
      "Verifica delle regole del contratto e del contratto collettivo",
      "Diffida con termine di pagamento, pronta da inviare",
      "Come procedere se il datore di lavoro non paga",
    ],
    needs: "Il contratto, le buste paga e, se lo avete, un conteggio delle ore.",
    note: "Le ore supplementari sono pagate con un supplemento del 25 %, salvo accordo scritto contrario (art. 321c CO). I crediti salariali si prescrivono in cinque anni (art. 128 CO).",
    faq: [
      { q: "Posso reclamare mentre lavoro ancora lì?", a: "Sì. La lettera è ferma ma corretta, per preservare il rapporto se restate." },
      { q: "E se il datore di lavoro non risponde?", a: "Potete adire l'autorità di conciliazione. Redigiamo l'istanza: prestazione «Istanza di conciliazione (lavoro)»." },
    ],
  },
  "lettre-de-demission": {
    name: "Lettera di dimissioni",
    short: "Una lettera che rispetta il termine di disdetta e regola in anticipo le vacanze residue e il certificato.",
    intro: "Una disdetta datata male può costarvi un mese di salario. Calcoliamo il vostro termine e redigiamo una lettera chiara, che regola anche le vacanze residue e il certificato di lavoro.",
    included: [
      "Calcolo del termine di disdetta e della data di fine",
      "Lettera di dimissioni personalizzata",
      "Richiesta del certificato di lavoro e punto sul saldo vacanze",
    ],
    needs: "Il contratto di lavoro e la data in cui desiderate partire.",
    note: "Salvo accordo diverso, il termine è di un mese nel primo anno, due mesi dal secondo al nono, tre mesi in seguito, per la fine di un mese (art. 335c CO). La lettera deve giungere al datore di lavoro prima dell'inizio del termine.",
    faq: [
      { q: "Posso partire prima?", a: "Solo con l'accordo del datore di lavoro. La lettera può proporre una data anticipata rispettando il termine legale." },
      { q: "Devo inviarla raccomandata?", a: "È consigliato per provare la ricezione, oppure consegnarla a mano contro firma." },
    ],
  },
  "requete-conciliation-travail": {
    name: "Rivolgersi all'autorità di conciliazione (lavoro)",
    short: "Il datore di lavoro non risponde più? Prepariamo l'istanza che depositate voi, con i documenti in ordine.",
    intro: "Il datore di lavoro non paga nonostante le vostre lettere? La procedura davanti al tribunale del lavoro inizia di regola con un tentativo di conciliazione. Redigiamo la vostra istanza e vi spieghiamo come si svolge l'udienza.",
    included: [
      "Istanza di conciliazione con conclusioni quantificate",
      "Elenco e ordinamento degli allegati",
      "Scheda di preparazione all'udienza di conciliazione",
    ],
    needs: "Il contratto, la corrispondenza con il datore di lavoro e i documenti che provano le vostre pretese.",
    note: "Per le controversie di lavoro fino a CHF 30'000 la procedura è semplificata e gratuita (art. 114 e 243 CPC). Depositate l'istanza voi stessi: Thrax Legal non vi rappresenta davanti alle autorità.",
    faq: [
      { q: "Devo partecipare all'udienza?", a: "Sì, la comparizione personale è di regola obbligatoria. La scheda vi aiuta a presentare la vostra posizione con calma." },
      { q: "E se il mio caso è complesso?", a: "Se serve un avvocato, ve lo diciamo prima che paghiate." },
    ],
  },
  "baisse-de-loyer": {
    name: "Chiedere una riduzione della pigione",
    short: "Quando il tasso ipotecario di riferimento scende, anche la pigione può scendere. Calcoliamo l'importo e scriviamo al locatore.",
    intro: "Quando il tasso ipotecario di riferimento scende, anche la vostra pigione può scendere. Verifichiamo il vostro diritto, calcoliamo la riduzione e redigiamo la lettera al locatore o all'amministrazione.",
    included: [
      "Verifica del tasso di riferimento e dell'ultimo adeguamento della pigione",
      "Calcolo della riduzione richiedibile",
      "Richiesta di riduzione, pronta da inviare",
      "Come procedere in caso di rifiuto",
    ],
    needs: "Il contratto di locazione e l'ultima notifica della pigione.",
    note: "La richiesta si fa per scritto per la prossima scadenza di disdetta. Il locatore ha 30 giorni per rispondere; in caso di rifiuto o silenzio potete adire l'autorità di conciliazione entro 30 giorni (art. 270a CO).",
    faq: [
      { q: "Il locatore può disdire perché ho chiesto una riduzione?", a: "No. Una disdetta data perché il conduttore fa valere i suoi diritti è annullabile (art. 271a CO)." },
      { q: "Quanto posso risparmiare?", a: "Dipende dall'ultimo adeguamento. Il calcolo vi indica l'importo esatto prima di inviare qualsiasi cosa." },
    ],
  },
  "contestation-loyer-initial": {
    name: "Contestare la pigione iniziale",
    short: "La nuova pigione vi sembra abusiva? Avete 30 giorni dalla consegna dell'alloggio. Analizziamo e prepariamo l'istanza.",
    intro: "Siete appena entrati e la pigione è molto più alta di quella del conduttore precedente? Forse potete contestarla. Valutiamo le vostre possibilità e redigiamo l'istanza all'autorità di conciliazione.",
    included: [
      "Analisi delle condizioni di contestazione",
      "Verifica del modulo ufficiale",
      "Istanza all'autorità di conciliazione, pronta da depositare",
      "Spiegazione della procedura e dei rischi",
    ],
    needs: "Il contratto, il modulo ufficiale ricevuto (se esiste) e la data di consegna delle chiavi.",
    note: "Il termine è di 30 giorni dalla consegna della cosa (art. 270 CO). In diversi cantoni il locatore deve comunicare la pigione precedente su modulo ufficiale: la sua mancanza può essere invocata.",
    faq: [
      { q: "Sono fuori termine, che fare?", a: "Se mancava il modulo ufficiale, esistono altre possibilità. Prenotate una chiamata giuridica per verificare." },
      { q: "È rischioso per il mio contratto?", a: "Il locatore non può disdire per questo motivo durante la procedura e nei tre anni successivi (art. 271a CO)." },
    ],
  },
  "defaut-logement": {
    name: "Riduzione della pigione per un difetto",
    short: "Muffa, riscaldamento guasto, cantiere rumoroso… Avvisiamo il locatore per iscritto e chiediamo la riduzione che vi spetta.",
    intro: "Muffa, riscaldamento guasto, infiltrazioni, cantiere rumoroso: un difetto che dura vi dà diritto a una riparazione e a una riduzione della pigione. Redigiamo l'avviso e la richiesta, nelle forme.",
    included: [
      "Qualifica del difetto e riduzione usuale",
      "Avviso dei difetti con termine di riparazione",
      "Richiesta di riduzione della pigione",
      "Spiegazione del deposito della pigione, se necessario",
    ],
    needs: "Foto del difetto, data della scoperta e corrispondenza con l'amministrazione.",
    note: "Non smettete mai di pagare la pigione: è un motivo di disdetta. Il deposito della pigione è possibile solo dopo un avviso scritto e un termine ragionevole (art. 259g CO). La riduzione è dovuta da quando il locatore conosce il difetto (art. 259d CO).",
    faq: [
      { q: "Di quanto può scendere la pigione?", a: "Dipende da gravità e durata. Vi indichiamo una forchetta basata sulla prassi." },
      { q: "E se l'amministrazione non reagisce?", a: "La lettera fissa un termine. Dopo potete depositare la pigione o adire l'autorità di conciliazione." },
    ],
  },
  "garantie-de-loyer": {
    name: "Recuperare la garanzia d'affitto",
    short: "Il vecchio locatore blocca la garanzia o vi addebita spese discutibili? Redigiamo il reclamo.",
    intro: "La vecchia amministrazione blocca la garanzia o vi addebita spese di ripristino? Verifichiamo cosa può davvero esservi chiesto e redigiamo la contestazione e la richiesta di liberazione.",
    included: [
      "Analisi del verbale di riconsegna e delle spese",
      "Distinzione tra usura normale e danni a vostro carico",
      "Lettera di contestazione e richiesta di liberazione della garanzia",
    ],
    needs: "Il contratto, i verbali di consegna e riconsegna e il conteggio dell'amministrazione.",
    note: "L'usura normale è a carico del locatore (art. 267 CO). Se entro un anno dalla fine della locazione il locatore non ha fatto valere pretese in giudizio o con un'esecuzione, potete chiedere alla banca di liberare la garanzia (art. 257e CO).",
    faq: [
      { q: "L'amministrazione può tenere la garanzia senza fare nulla?", a: "Non all'infinito: dopo un anno senza procedura potete chiedere la liberazione direttamente alla banca." },
      { q: "Mi addebitano una tinteggiatura completa, è normale?", a: "Spesso no: si tiene conto della durata di vita della pittura. La lettera contesta gli importi ingiustificati." },
    ],
  },
  "resiliation-anticipee-bail": {
    name: "Lasciare l'alloggio prima della scadenza",
    short: "Redigiamo la disdetta e la presentazione di un inquilino subentrante, per non pagare la pigione fino al termine.",
    intro: "Dovete traslocare prima della scadenza? Presentando un conduttore subentrante potete liberarvi prima. Redigiamo la lettera di disdetta e la presentazione del candidato.",
    included: [
      "Calcolo della scadenza ordinaria e dei termini",
      "Lettera di disdetta anticipata conforme",
      "Lettera di presentazione del conduttore subentrante",
    ],
    needs: "Il contratto e, se li avete già, i dati del conduttore subentrante.",
    note: "Il subentrante deve essere solvibile, accettabile per il locatore e disposto a riprendere il contratto alle stesse condizioni (art. 264 CO). Per l'abitazione familiare la disdetta deve essere firmata da entrambi i coniugi (art. 266m CO).",
    faq: [
      { q: "Il locatore può rifiutare il mio candidato?", a: "Solo per gravi motivi. Altrimenti siete liberati alla data proposta." },
      { q: "Quanti candidati servono?", a: "Ne basta uno se adempie le condizioni. Presentarne due o tre accelera le cose." },
    ],
  },
  "contestation-conge": {
    name: "Contestare una disdetta o chiedere una proroga",
    short: "Avete 30 giorni dalla ricezione della disdetta. Prepariamo l'istanza all'autorità di conciliazione.",
    intro: "Avete ricevuto la disdetta? Potete contestarla se è abusiva, o chiedere una protrazione se il trasloco vi crea gravi difficoltà. Redigiamo l'istanza all'autorità di conciliazione.",
    included: [
      "Verifica della validità formale della disdetta",
      "Analisi dei motivi: annullabile o no",
      "Istanza di annullamento e/o di protrazione, pronta da depositare",
    ],
    needs: "Il modulo ufficiale di disdetta, la busta o l'avviso di ritiro e il contratto.",
    note: "Il termine è di 30 giorni dalla ricezione della disdetta (art. 273 CO). Una disdetta non data su modulo ufficiale è nulla (art. 266l e 266o CO). La protrazione può arrivare a quattro anni per un'abitazione (art. 272b CO).",
    faq: [
      { q: "Da quando decorre il termine?", a: "Dalla ricezione effettiva o dall'ultimo giorno di giacenza alla posta. Scegliete express se la data si avvicina." },
      { q: "Guadagno tempo anche se la disdetta è valida?", a: "Spesso sì: una protrazione può essere concessa in caso di rigore." },
    ],
  },
  "decompte-de-charges": {
    name: "Verificare un conteggio delle spese accessorie",
    short: "Controlliamo il conteggio riga per riga e scriviamo al locatore per ogni voce discutibile.",
    intro: "Il conteggio di riscaldamento e spese accessorie è esploso? Verifichiamo ogni voce e redigiamo il reclamo all'amministrazione, con la richiesta di consultare i giustificativi.",
    included: [
      "Controllo delle voci rispetto al contratto",
      "Individuazione delle spese non pattuite o eccessive",
      "Lettera di reclamo e richiesta dei giustificativi",
    ],
    needs: "Il contratto e il conteggio contestato.",
    note: "Dovete solo le spese accessorie espressamente pattuite nel contratto (art. 257a CO) e avete il diritto di consultare i giustificativi (art. 257b CO).",
    faq: [
      { q: "Devo pagare il saldo nel frattempo?", a: "Vi indichiamo quale parte pagare e quale contestare." },
      { q: "Posso contestare un conteggio vecchio?", a: "Spesso sì, entro certi limiti. Indicate gli anni interessati." },
    ],
  },
  "litige-de-voisinage": {
    name: "Lite con un vicino",
    short: "Quando parlare non basta più, una lettera pacata e fondata sul diritto, per rumore, una siepe o un confine.",
    intro: "Le discussioni non hanno portato a nulla e la situazione si protrae? Una lettera formale, pacata e giuridicamente fondata risolve spesso il problema senza processo. La redigiamo per voi.",
    included: [
      "Analisi della situazione e delle regole applicabili",
      "Lettera formale al vicino o all'amministrazione",
      "Consigli per raccogliere le prove",
    ],
    needs: "Una descrizione del problema, la sua durata e, se le avete, foto o un diario delle immissioni.",
    note: "Ognuno deve astenersi da ogni eccesso pregiudizievole ai vicini (art. 684 CC). Le distanze di alberi e piante sono fissate dal diritto cantonale.",
    faq: [
      { q: "La lettera non peggiorerà le cose?", a: "È ferma ma cortese, per aprire una soluzione piuttosto che un conflitto." },
      { q: "Sono conduttore, a chi scrivo?", a: "Spesso all'amministrazione, che deve garantire un uso tranquillo dell'abitazione. Vi diciamo a chi." },
    ],
  },
  "resiliation-de-contrat": {
    name: "Disdire un abbonamento o un contratto",
    short: "Verifichiamo quando potete uscire dall'abbonamento (palestra, telefono, assicurazione…) e redigiamo una disdetta valida.",
    intro: "Un abbonamento che si rinnova da solo, un'assicurazione che rifiuta la disdetta, una palestra che non risponde: verifichiamo il contratto e redigiamo una disdetta che regge.",
    included: [
      "Verifica delle condizioni di disdetta",
      "Calcolo della data di fine possibile",
      "Lettera di disdetta pronta da inviare",
    ],
    needs: "Il contratto o le condizioni generali e la data in cui volete smettere.",
    note: "Una disdetta tardiva ha effetto solo alla scadenza successiva. Il contratto d'assicurazione può in linea di principio essere disdetto per la fine del terzo anno, poi ogni anno (art. 35a LCA).",
    faq: [
      { q: "Il fornitore rifiuta la mia disdetta?", a: "Se rispetta il contratto, produce effetto anche senza il suo accordo. La lettera lo ricorda chiaramente." },
      { q: "Posso disdire per gravi motivi?", a: "In certi casi sì. Descrivete la vostra situazione, verifichiamo." },
    ],
  },
  "garantie-achat-defectueux": {
    name: "Far valere la garanzia di un acquisto",
    short: "L'oggetto è guasto o non è quello che vi hanno venduto? Scriviamo al venditore per ottenere ciò che vi spetta.",
    intro: "Un apparecchio, un mobile o un veicolo difettoso, e il venditore scarica la responsabilità? Verifichiamo i vostri diritti di garanzia e redigiamo la diffida.",
    included: [
      "Analisi della garanzia legale e contrattuale",
      "Scelta della richiesta più favorevole: riparazione, sostituzione, riduzione o risoluzione",
      "Diffida al venditore, pronta da inviare",
    ],
    needs: "Fattura o scontrino, condizioni di garanzia e foto del difetto.",
    note: "Il difetto va segnalato al venditore appena scoperto (art. 201 CO). Per un bene nuovo acquistato da un consumatore, il termine di due anni non può essere abbreviato (art. 210 CO).",
    faq: [
      { q: "Il venditore mi rimanda al produttore?", a: "La garanzia legale vincola il venditore. La lettera ricorda che resta il vostro interlocutore." },
      { q: "E per un acquisto online?", a: "Le regole sono le stesse per un venditore in Svizzera. Per uno estero vi indichiamo il diritto applicabile." },
    ],
  },
  "litige-artisan": {
    name: "Lite con un artigiano",
    short: "Lavori fatti male, in ritardo o più cari del previsto? Segnaliamo i difetti per iscritto e fissiamo un termine all'impresa.",
    intro: "Lavori fatti male, cantiere infinito, fattura ben oltre il preventivo: analizziamo il contratto e redigiamo l'avviso dei difetti e la diffida all'artigiano.",
    included: [
      "Analisi di contratto, preventivo e fatture",
      "Avviso dei difetti nelle forme",
      "Diffida: rifacimento, termine o riduzione del prezzo",
    ],
    needs: "Preventivo o contratto, fatture, foto e corrispondenza con l'impresa.",
    note: "I difetti vanno segnalati rapidamente dopo la scoperta. Se un preventivo approssimativo è superato in modo eccessivo, potete chiedere una riduzione o recedere dal contratto (art. 375 CO).",
    faq: [
      { q: "Devo pagare la fattura nel frattempo?", a: "Vi indichiamo quale parte pagare e quale trattenere, senza mettervi in torto." },
      { q: "E se si applica la norma SIA 118?", a: "Ne teniamo conto: prevede regole e termini propri per i difetti." },
    ],
  },
  "contester-une-facture": {
    name: "Contestare una fattura",
    short: "Una fattura che non corrisponde a quanto ordinato? Redigiamo una contestazione motivata.",
    intro: "Una fattura per una prestazione mai ordinata, un importo gonfiato, spese a sorpresa: redigiamo una contestazione chiara che spiega perché non dovete quell'importo.",
    included: [
      "Analisi della fattura e di quanto pattuito",
      "Lettera di contestazione motivata",
      "Come procedere in caso di sollecito o esecuzione",
    ],
    needs: "La fattura contestata, il contratto o l'offerta e la corrispondenza.",
    note: "Pagare «per stare tranquilli» equivale spesso a riconoscere il debito. In caso di precetto esecutivo avete 10 giorni per fare opposizione (art. 74 LEF).",
    faq: [
      { q: "Devo pagare la parte non contestata?", a: "Sì, dimostra la vostra buona fede. La lettera precisa l'importo riconosciuto." },
      { q: "E se l'impresa avvia un'esecuzione?", a: "Fate opposizione entro 10 giorni. Vedi «Esecuzione ingiustificata»." },
    ],
  },
  "relecture-contrat-particulier": {
    name: "Verificare un contratto prima di firmare",
    short: "Leasing, credito, acquisto di un'auto o preventivo di lavori: lo leggiamo prima di voi e vi mostriamo le trappole.",
    intro: "Prima di firmare un contratto importante, fatelo rileggere. Vi segnaliamo le clausole sfavorevoli, i costi nascosti e cosa potete negoziare.",
    included: [
      "Rilettura completa (fino a 15 pagine)",
      "Elenco dei rischi e delle clausole insolite",
      "Proposte di modifica",
    ],
    needs: "Il contratto, le condizioni generali e l'eventuale offerta.",
    note: "Per un leasing o un credito al consumo potete revocare il vostro consenso entro 14 giorni (art. 16 LCC).",
    faq: [
      { q: "Il contratto supera le 15 pagine?", a: "Ordinate comunque: confermiamo il prezzo esatto prima di iniziare." },
      { q: "In quanto tempo?", a: "Tre giorni lavorativi, o 24 ore con l'opzione express." },
    ],
  },
  "vol-annule-retarde": {
    name: "Indennizzo per un volo cancellato o in ritardo",
    short: "Scriviamo noi alla compagnia aerea. Pagate un prezzo fisso e tenete tutto l'indennizzo.",
    intro: "Cancellazione, overbooking, forte ritardo: potreste avere diritto a 250-600 euro per passeggero. Verifichiamo il vostro diritto e redigiamo il reclamo, senza trattenere percentuali.",
    included: [
      "Verifica del diritto e dell'importo",
      "Reclamo alla compagnia, pronto da inviare",
      "Come procedere in caso di rifiuto",
    ],
    needs: "La prenotazione, la carta d'imbarco e quanto comunicato dalla compagnia.",
    note: "Il regolamento europeo sui diritti dei passeggeri aerei si applica anche in Svizzera, in particolare ai voli in partenza da aeroporti svizzeri. Circostanze eccezionali (meteo, sciopero dei controllori) possono escludere l'indennizzo.",
    faq: [
      { q: "Perché non una piattaforma di reclami?", a: "Trattengono spesso il 25-35 % dell'indennizzo. Qui pagate un prezzo fisso e tenete il resto." },
      { q: "Per più passeggeri?", a: "Un solo ordine copre tutte le persone della stessa prenotazione." },
    ],
  },
  "refus-assurance": {
    name: "Contestare il rifiuto di un'assicurazione",
    short: "L'assicurazione mobilia domestica, viaggio o veicolo rifiuta di pagare? Rispondiamo per iscritto, contratto alla mano.",
    intro: "La vostra assicurazione rifiuta di pagare o rimborsa solo in parte? Analizziamo polizza e decisione e redigiamo un reclamo motivato.",
    included: [
      "Analisi di polizza, condizioni generali e rifiuto",
      "Argomenti giuridici e contrattuali",
      "Reclamo all'assicuratore, pronto da inviare",
      "Come procedere: ombudsman, procedura",
    ],
    needs: "Polizza, condizioni generali, lettera di rifiuto e documenti del sinistro.",
    note: "Le pretese derivanti dal contratto d'assicurazione si prescrivono di regola in cinque anni (art. 46 LCA). L'ombudsman dell'assicurazione privata interviene gratuitamente.",
    faq: [
      { q: "E per una cassa malati (LAMal)?", a: "È un'assicurazione sociale: vedi «Opposizione a una decisione di assicurazione sociale»." },
      { q: "L'assicuratore invoca un'esclusione?", a: "Non è per forza la fine: le esclusioni devono essere chiare e nel dubbio si interpretano a favore dell'assicurato." },
    ],
  },
  "poursuite-injustifiee": {
    name: "Difendersi da un'esecuzione ingiustificata",
    short: "Avete 10 giorni per fare opposizione. Ce ne occupiamo noi e, al momento giusto, chiediamo che l'esecuzione sparisca dal vostro estratto.",
    intro: "Avete ricevuto un precetto esecutivo per un debito che contestate? Vi spieghiamo come fare opposizione e redigiamo poi la domanda di non comunicazione, perché l'esecuzione non compaia più nell'estratto.",
    included: [
      "Verifica del precetto esecutivo e dei termini",
      "Istruzioni per l'opposizione",
      "Domanda di non comunicazione all'ufficio d'esecuzione, al momento giusto",
    ],
    needs: "Il precetto esecutivo (foto o PDF) e ciò che sapete del credito.",
    note: "L'opposizione va fatta entro 10 giorni dalla notifica (art. 74 LEF). Dopo tre mesi potete chiedere che l'esecuzione non sia più comunicata a terzi se il creditore non ha agito (art. 8a LEF).",
    faq: [
      { q: "L'opposizione costa qualcosa?", a: "No, è gratuita e non deve essere motivata." },
      { q: "L'esecuzione sparisce davvero?", a: "Non è più comunicata a terzi, ad esempio a un futuro locatore, se il creditore non ha proseguito la procedura." },
    ],
  },
  "recuperer-argent-prete": {
    name: "Recuperare denaro prestato",
    short: "Qualcuno non vi restituisce i soldi? Prima una diffida, poi la domanda d'esecuzione, pronta da depositare.",
    intro: "Avete prestato denaro a una persona vicina, venduto qualcosa senza essere pagati o anticipato spese? Redigiamo la diffida e prepariamo la domanda d'esecuzione se nulla si muove.",
    included: [
      "Analisi delle prove del credito",
      "Diffida con termine di pagamento",
      "Domanda d'esecuzione preparata, pronta da depositare",
    ],
    needs: "Le prove del prestito o del debito: messaggi, bonifici, riconoscimento di debito.",
    note: "Un prestito senza scadenza va restituito entro sei settimane dalla prima richiesta (art. 318 CO). Un riconoscimento di debito firmato facilita molto il seguito (art. 82 LEF).",
    faq: [
      { q: "Non ho un contratto scritto, è possibile?", a: "Sì: messaggi, bonifici e testimoni possono provare il prestito. Valutiamo la solidità delle prove." },
      { q: "E se il debitore fa opposizione?", a: "Servirà il rigetto dell'opposizione o un'azione in giudizio. Vi spieghiamo il seguito e i costi." },
    ],
  },
  "reclamation-taxation-impots": {
    name: "Contestare la tassazione",
    short: "Una deduzione rifiutata o un reddito calcolato male? Avete 30 giorni per il reclamo. Lo redigiamo noi.",
    intro: "La decisione di tassazione non corrisponde alla vostra dichiarazione? Deduzione rifiutata, tassazione d'ufficio, errore di calcolo: redigiamo un reclamo motivato.",
    included: [
      "Confronto tra dichiarazione e decisione",
      "Argomenti e documenti da allegare",
      "Reclamo pronto da inviare",
    ],
    needs: "La decisione di tassazione, la dichiarazione e i giustificativi interessati.",
    note: "Il reclamo va presentato entro 30 giorni dalla notifica, per scritto e motivato (art. 132 LIFD per l'imposta federale diretta, regole simili nei cantoni).",
    faq: [
      { q: "Il termine di 30 giorni può essere prorogato?", a: "No, è legale. Se la data si avvicina, scegliete express." },
      { q: "L'imposta può aumentare dopo un reclamo?", a: "L'autorità riesamina tutta la tassazione: verifichiamo questo rischio prima di depositare." },
    ],
  },
  "opposition-assurance-sociale": {
    name: "Opporsi a una decisione delle assicurazioni sociali",
    short: "Disoccupazione, AVS, cassa malati o assicurazione infortuni hanno deciso in modo che vi sembra sbagliato? Redigiamo l'opposizione entro 30 giorni.",
    intro: "Giorni di sospensione alla disoccupazione, prestazione rifiutata dalla cassa malati, rendita calcolata troppo bassa: analizziamo la decisione e redigiamo la vostra opposizione.",
    included: [
      "Analisi della decisione e delle regole applicabili",
      "Argomenti e documenti da allegare",
      "Opposizione pronta da inviare",
    ],
    needs: "La decisione, la corrispondenza e i documenti utili (certificati, contratti, attestati).",
    note: "L'opposizione va presentata entro 30 giorni (art. 52 LPGA). Per l'assicurazione invalidità la procedura è diversa: osservazioni sul progetto di decisione, poi ricorso.",
    faq: [
      { q: "L'opposizione è gratuita?", a: "Sì, la procedura d'opposizione è di regola gratuita." },
      { q: "E se viene respinta?", a: "È possibile un ricorso al tribunale cantonale entro 30 giorni. Vi diciamo se è consigliabile un avvocato." },
    ],
  },
  testament: {
    name: "Redigere il testamento",
    short: "Prepariamo con voi un testamento adatto alla vostra famiglia e al diritto attuale. Poi lo ricopiate a mano.",
    intro: "Favorire il coniuge, proteggere il partner, lasciare un bene preciso: vi aiutiamo a redigere un testamento chiaro, conforme al diritto successorio in vigore dal 2023, che ricopiate a mano.",
    included: [
      "Calcolo delle porzioni legittime e della quota disponibile",
      "Testo del testamento secondo le vostre volontà",
      "Istruzioni per ricopiarlo, datarlo, firmarlo e conservarlo",
    ],
    needs: "La situazione familiare, i beni principali e cosa desiderate trasmettere, a chi.",
    note: "Il testamento olografo deve essere interamente scritto a mano, datato e firmato (art. 505 CC). Dal 2023 i genitori non hanno più una legittima e quella dei discendenti è ridotta alla metà della loro quota legale.",
    faq: [
      { q: "Serve il notaio?", a: "No per un testamento olografo. Un testamento pubblico resta consigliato nelle situazioni complesse." },
      { q: "Il mio partner non sposato eredita?", a: "No, salvo testamento. È proprio ciò che il testamento può prevedere." },
    ],
  },
  "mandat-pour-cause-d-inaptitude": {
    name: "Mandato precauzionale",
    short: "Scegliete in anticipo chi si occuperà dei vostri soldi, dei vostri documenti e delle decisioni sulla salute se non potrete più farlo.",
    intro: "Infortunio, malattia: se non potete più gestire i vostri affari, l'autorità di protezione designa qualcuno. Con un mandato precauzionale scegliete voi. Lo redigiamo con voi.",
    included: [
      "Scelta degli ambiti: cura della persona, patrimonio, rappresentanza",
      "Testo del mandato adattato alla vostra situazione",
      "Istruzioni su forma e registrazione",
    ],
    needs: "La persona o le persone scelte e ciò che desiderate affidare loro.",
    note: "Il mandato deve essere interamente scritto a mano, datato e firmato, oppure costituito per atto pubblico (art. 361 CC). La sua esistenza può essere iscritta presso lo stato civile.",
    faq: [
      { q: "Il mio coniuge non può già rappresentarmi?", a: "Solo per gli affari correnti (art. 374 CC). Il mandato va oltre." },
      { q: "Posso modificarlo?", a: "Sì, in ogni momento, finché siete capaci di discernimento." },
    ],
  },
  "directives-anticipees": {
    name: "Direttive anticipate",
    short: "Mettete per iscritto le cure che volete o rifiutate e indicate chi parlerà per voi.",
    intro: "Quali trattamenti accettare o rifiutare se non potete più esprimervi? Le direttive del paziente lo dicono chiaramente e designano la persona che parlerà per voi.",
    included: [
      "Questionario guidato sulle vostre volontà",
      "Direttive redatte in termini precisi",
      "Designazione di un rappresentante terapeutico",
    ],
    needs: "I vostri desideri e la persona di fiducia da designare.",
    note: "Le direttive devono essere scritte, datate e firmate (art. 371 CC). Possono essere annotate sulla tessera d'assicurato.",
    faq: [
      { q: "Il medico deve rispettarle?", a: "Sì, salvo se violano la legge o non corrispondono più alla vostra volontà presumibile (art. 372 CC)." },
      { q: "Serve un notaio?", a: "No, basta la forma scritta, datata e firmata." },
    ],
  },
  "convention-de-concubinage": {
    name: "Contratto di concubinato",
    short: "Vivete insieme senza essere sposati? Mettiamo per iscritto chi paga cosa e chi tiene cosa in caso di separazione.",
    intro: "Le coppie non sposate non hanno quasi alcuna regola legale che le protegga. Un contratto di convivenza regola abitazione, spese, beni acquistati insieme e cosa succede in caso di separazione.",
    included: [
      "Analisi della vostra situazione comune",
      "Contratto su misura: abitazione, spese, beni, separazione",
      "Raccomandazioni: testamento, previdenza, assicurazione",
    ],
    needs: "La vostra situazione: abitazione, redditi, beni comuni, eventuali figli.",
    note: "Nella convivenza nessun partner eredita dall'altro senza testamento, e l'abitazione comune non è protetta come quella dei coniugi.",
    faq: [
      { q: "Il contratto è valido senza notaio?", a: "Sì, basta un contratto scritto e firmato da entrambi." },
      { q: "E se abbiamo figli?", a: "Integriamo i punti utili e vi indichiamo cosa regolare presso l'autorità (autorità parentale, mantenimento)." },
    ],
  },
  "separation-divorce-amiable": {
    name: "Divorzio consensuale senza figli minorenni",
    short: "Siete d'accordo sull'essenziale? Redigiamo la convenzione e la richiesta comune al tribunale.",
    intro: "Siete d'accordo sull'essenziale, non avete figli minorenni e volete evitare una procedura lunga? Redigiamo, in modo neutrale e per entrambi, la convenzione di divorzio e la richiesta comune che depositate in tribunale.",
    included: [
      "Colloquio preliminare con entrambi i coniugi",
      "Convenzione: abitazione, mantenimento, beni, divisione della previdenza professionale",
      "Richiesta comune di divorzio pronta da depositare, con l'elenco dei documenti",
    ],
    needs: "Redditi, attestati di previdenza (2° pilastro) di ciascuno ed elenco dei beni.",
    note: "Il divorzio su richiesta comune non richiede un avvocato: i coniugi depositano personalmente richiesta e convenzione (art. 111 CC). Il giudice verifica che la convenzione sia chiara, completa ed equa. Interveniamo in modo neutrale per entrambi i coniugi e solo con il loro accordo.",
    faq: [
      { q: "E se abbiamo figli minorenni?", a: "Non trattiamo questi casi: autorità parentale, custodia e mantenimento richiedono un mediatore familiare o un avvocato. Vi orientiamo." },
      { q: "Perché «da CHF 590»?", a: "Il prezzo vale per una situazione semplice, senza immobili né impresa. È confermato per scritto dopo il primo scambio, prima di qualsiasi pagamento." },
    ],
  },
  "question-juridique": {
    name: "Porre una domanda giuridica",
    short: "Ponete una domanda precisa, vi rispondiamo per iscritto citando gli articoli di legge che si applicano.",
    intro: "Avete una domanda precisa e volete una risposta affidabile, senza appuntamento? Ponetela: ricevete una risposta scritta, chiara, con i passi da seguire.",
    included: [
      "Ricerca giuridica sulla vostra domanda",
      "Risposta scritta chiara, con le basi legali",
      "Prossimo passo consigliato",
    ],
    needs: "La vostra domanda e il contesto in poche righe.",
    note: "Una domanda rapida riguarda un punto preciso. Se la vostra situazione richiede un documento o un'analisi completa, vi proponiamo prima la prestazione adatta.",
    faq: [
      { q: "E una domanda di seguito?", a: "Una precisazione sulla risposta ricevuta è inclusa." },
      { q: "Quali ambiti?", a: "Lavoro, locazione, consumo, contratti, esecuzioni, famiglia semplice. Per il penale vi indirizziamo a un avvocato." },
    ],
  },
  "appel-juridique": {
    name: "Una chiamata di 20 minuti",
    short: "Ci raccontate la situazione al telefono, vi diciamo cosa potete fare e quali termini tenere d'occhio.",
    intro: "Preferite parlarne? Prenotate una chiamata di 20 minuti: esponete la vostra situazione e vi diciamo cosa potete fare, entro quali termini e cosa evitare.",
    included: [
      "Chiamata telefonica o video di 20 minuti",
      "Preparazione sulla base della vostra descrizione scritta",
      "Riepilogo scritto dei prossimi passi",
    ],
    needs: "Una descrizione della situazione e le vostre disponibilità.",
    note: "Se ordinate poi una prestazione legata alla chiamata entro 30 giorni, il prezzo della chiamata viene dedotto.",
    faq: [
      { q: "Quando avviene la chiamata?", a: "Vi proponiamo fasce orarie entro due giorni lavorativi." },
      { q: "E se 20 minuti non bastano?", a: "Il riepilogo scritto indica la prestazione adatta e il suo prezzo fisso." },
    ],
  },
  "lettre-juridique-sur-mesure": {
    name: "Lettera su misura",
    short: "Per una lettera formale che non rientra in nessun'altra categoria. La redigiamo per il vostro caso.",
    intro: "La vostra situazione non rientra in nessuna casella? Redigiamo la lettera formale che vi serve: reclamo, contestazione, richiesta, diffida.",
    included: [
      "Analisi della situazione",
      "Lettera giuridicamente fondata, pronta da inviare",
      "Un giro di correzioni",
    ],
    needs: "La situazione, il destinatario e i documenti utili.",
    note: "Una lettera ben redatta fissa un termine, cita le regole giuste e lascia una traccia scritta utile in caso di procedura.",
    faq: [
      { q: "La lettera è firmata da Thrax Legal?", a: "No, è redatta a vostro nome e la inviate voi." },
      { q: "E se la situazione è più complessa?", a: "Ve lo diciamo prima di iniziare e vi indichiamo il prezzo adatto." },
    ],
  },
  "mise-en-demeure": {
    name: "Diffida",
    short: "Una lettera formale che ricorda quanto vi è dovuto, fissa un termine e annuncia chiaramente cosa succederà dopo.",
    intro: "Qualcuno non rispetta i propri impegni verso la vostra impresa? Un cliente che non paga, un fornitore che non consegna, un conduttore in ritardo, un partner che non mantiene la parola: una diffida formale, con termine e seguito annunciato, sblocca spesso la situazione.",
    included: [
      "Verifica dei vostri diritti e dei documenti",
      "Calcolo degli interessi di mora per una somma di denaro",
      "Diffida pronta da inviare, sulla vostra carta intestata",
    ],
    needs: "Il contratto, l'ordine o la fattura interessata e la corrispondenza con l'altra parte.",
    note: "Per una somma di denaro è dovuto un interesse di mora del 5 % annuo dalla mora (art. 104 CO). Per una prestazione non fornita, la diffida con un termine supplementare dà il diritto di rinunciare alla prestazione o di recedere dal contratto (art. 107 CO).",
    faq: [
      { q: "Raccomandata?", a: "Consigliata per provare la ricezione. Un invio parallelo via email accelera spesso la reazione." },
      { q: "E se l'altra parte ancora non reagisce?", a: "Per una fattura, passate all'incasso completo. Altrimenti vi indichiamo il seguito: recesso, risarcimento o procedura." },
    ],
  },
  "recouvrement-facture-impayee": {
    name: "Recuperare una fattura non pagata",
    short: "Scriviamo al cliente, prepariamo la domanda d'esecuzione e vi diciamo cosa fare se fa opposizione.",
    intro: "Una fattura non pagata da settimane? Ci occupiamo dell'intero percorso bonale e della preparazione dell'esecuzione, fino all'istanza di rigetto se il debitore fa opposizione.",
    included: [
      "Diffida con interessi",
      "Domanda d'esecuzione preparata, pronta da depositare",
      "Analisi dell'eventuale opposizione e del seguito",
      "Consigli per preservare il rapporto con il cliente, se possibile",
    ],
    needs: "La fattura, il contratto o l'ordine, i solleciti e i dati del debitore.",
    note: "I crediti si prescrivono di regola in dieci anni, ma in cinque per molte prestazioni correnti (art. 127 e 128 CO). Depositate voi la domanda: la rappresentanza professionale davanti agli uffici d'esecuzione è disciplinata dai cantoni.",
    faq: [
      { q: "Perché non una società d'incasso?", a: "Prendono una percentuale o addebitano spese al debitore, talvolta contestate. Qui il prezzo è fisso e il rapporto con il cliente è preservato." },
      { q: "Più fatture dello stesso cliente?", a: "Una sola prestazione copre tutte le fatture dello stesso debitore." },
    ],
  },
  "requete-de-mainlevee": {
    name: "Istanza di rigetto dell'opposizione",
    short: "Il debitore ha fatto opposizione? Prepariamo l'istanza al tribunale e ordiniamo i vostri documenti.",
    intro: "Il debitore ha fatto opposizione al precetto esecutivo? Con un riconoscimento di debito o una sentenza potete proseguire l'esecuzione con il rigetto dell'opposizione. Redigiamo l'istanza.",
    included: [
      "Verifica del titolo: riconoscimento di debito o sentenza",
      "Istanza di rigetto provvisorio o definitivo, pronta da depositare",
      "Elenco degli allegati",
    ],
    needs: "Il precetto con l'opposizione, il contratto firmato o il riconoscimento di debito e le fatture.",
    note: "Un riconoscimento di debito firmato consente il rigetto provvisorio (art. 82 LEF), una sentenza esecutiva il rigetto definitivo (art. 80 LEF). Senza titolo occorre un'azione di riconoscimento del debito.",
    faq: [
      { q: "Basta un contratto firmato?", a: "Spesso sì, se la prestazione è stata fornita e l'importo risulta chiaramente dal contratto." },
      { q: "Chi deposita l'istanza?", a: "Voi, presso il tribunale competente. Vi diciamo quale e come." },
    ],
  },
  "litige-commercial": {
    name: "Lite con un cliente, un fornitore o un partner",
    short: "Analizziamo il caso, vi diciamo a che punto siete e difendiamo la vostra posizione per iscritto.",
    intro: "Consegna non conforme, prestazione contestata, rottura del contratto: analizziamo la situazione e redigiamo la lettera che difende la vostra posizione e apre a una soluzione.",
    included: [
      "Analisi del contratto e della corrispondenza",
      "Valutazione della vostra posizione e dei rischi",
      "Lettera formale alla controparte",
    ],
    needs: "Il contratto, le fatture e la corrispondenza importante.",
    note: "Gli scritti contano: una lettera precisa, inviata presto, rafforza la vostra posizione in caso di procedura.",
    faq: [
      { q: "E se si va in tribunale?", a: "Vi indirizziamo a un avvocato e gli trasmettiamo un dossier ordinato." },
      { q: "Potete negoziare per noi?", a: "Prepariamo lettere e argomenti; restate voi l'interlocutore." },
    ],
  },
  "cgv-sur-mesure": {
    name: "Condizioni generali (CG) su misura",
    short: "CG scritte per la vostra attività reale, che regolano i ritardi di pagamento, la responsabilità e il foro competente.",
    intro: "CG copiate da un concorrente non vi proteggono. Redigiamo condizioni generali adatte alla vostra attività, ai vostri clienti (imprese o consumatori) e al vostro modo di vendere.",
    included: [
      "Questionario su attività e rischi",
      "CG complete: ordine, prezzo, pagamento, mora, garanzia, responsabilità, foro",
      "Consigli per integrarle validamente (sito, offerte, fatture)",
      "Un giro di correzioni",
    ],
    needs: "Una descrizione dell'attività e i documenti attuali (offerta, fattura, CG esistenti).",
    note: "Le CG si applicano solo se il cliente ha potuto prenderne conoscenza prima di concludere. Verso i consumatori le clausole squilibrate sono sleali (art. 8 LCSl).",
    faq: [
      { q: "Il negozio online ha bisogno di CG separate?", a: "Spesso sì, o di un capitolo dedicato. Lo integriamo se vendete online." },
      { q: "In quali lingue?", a: "In francese di default. Una traduzione è possibile su preventivo." },
    ],
  },
  "contrat-commercial-sur-mesure": {
    name: "Contratto commerciale su misura",
    short: "Un contratto di prestazione, subappalto, distribuzione o partenariato, scritto a partire dalla vostra situazione.",
    intro: "Un accordo importante merita un vero contratto. Redigiamo un contratto adatto al vostro rapporto commerciale, con le clausole che proteggono i vostri interessi.",
    included: [
      "Inquadramento dell'accordo e dei rischi",
      "Contratto completo: oggetto, prezzo, termini, responsabilità, disdetta, foro",
      "Un giro di correzioni",
    ],
    needs: "I punti concordati con il partner e i documenti esistenti.",
    note: "La maggior parte dei contratti commerciali non richiede forme particolari, ma uno scritto chiaro evita la maggior parte delle controversie.",
    faq: [
      { q: "E se la controparte propone il suo contratto?", a: "Scegliete piuttosto la verifica di contratto commerciale." },
      { q: "Contratto in inglese?", a: "Possibile, prezzo confermato prima di iniziare." },
    ],
  },
  "relecture-contrat-commercial": {
    name: "Verificare un contratto commerciale",
    short: "Prima della firma rileggiamo il contratto (fino a 20 pagine), vi segnaliamo i rischi e proponiamo correzioni.",
    intro: "Un cliente o un fornitore vi sottopone il suo contratto? Lo rileggiamo, segnaliamo le clausole pericolose e proponiamo correzioni da negoziare.",
    included: [
      "Rilettura completa (fino a 20 pagine)",
      "Rischi classificati per priorità",
      "Correzioni proposte in revisione",
    ],
    needs: "Il contratto (Word di preferenza) e il contesto del rapporto.",
    note: "Le clausole di responsabilità, penale, durata e foro sono quelle che costano di più in caso di problema.",
    faq: [
      { q: "Più di 20 pagine?", a: "Il prezzo è confermato prima di iniziare, per blocco di 20 pagine." },
      { q: "Contratto in inglese?", a: "Sì, la verifica in inglese è possibile." },
    ],
  },
  "accord-de-confidentialite": {
    name: "Accordo di riservatezza (NDA)",
    short: "Prima di condividere un progetto o dei numeri: un accordo unilaterale o reciproco, con una penale in caso di fuga di notizie.",
    intro: "Prima di presentare un progetto, un know-how o delle cifre, proteggeteli. Redigiamo un accordo di riservatezza adatto alla vostra situazione.",
    included: [
      "Scelta tra accordo unilaterale e reciproco",
      "Definizione precisa delle informazioni protette",
      "Penale convenzionale e durata adeguate",
    ],
    needs: "Le parti, il progetto e le informazioni da proteggere.",
    note: "Una pena convenzionale (art. 160 segg. CO) evita di dover provare l'importo esatto del danno in caso di violazione.",
    faq: [
      { q: "Un modello gratuito non basta?", a: "Spesso protegge male ciò che conta per voi o prevede una penale inapplicabile." },
      { q: "In inglese?", a: "Sì, senza supplemento per un NDA standard." },
    ],
  },
  "contrat-de-mandat-independant": {
    name: "Contratto per indipendenti (mandato)",
    short: "Per freelance e consulenti, un contratto che fissa l'incarico, l'onorario e a chi appartiene il lavoro consegnato.",
    intro: "Che siate freelance o che incarichiate un indipendente, un contratto chiaro evita malintesi e il rischio di riqualifica in contratto di lavoro.",
    included: [
      "Mandato o contratto d'appalto secondo l'incarico",
      "Clausole su onorari, responsabilità e proprietà intellettuale",
      "Punti d'attenzione sullo statuto d'indipendente",
    ],
    needs: "Incarico, durata, onorari e parti.",
    note: "Lo statuto d'indipendente ai fini AVS dipende dalla realtà della collaborazione, non solo dal contratto. Il mandato può essere revocato in ogni tempo da ciascuna parte (art. 404 CO).",
    faq: [
      { q: "Mandato o appalto?", a: "Dipende dal risultato promesso. Scegliamo la qualifica adatta e ve la spieghiamo." },
      { q: "Per più clienti?", a: "Possiamo redigere un modello riutilizzabile; indicatelo nella richiesta." },
    ],
  },
  "contrat-de-travail-sur-mesure": {
    name: "Contratto di lavoro su misura",
    short: "Scritto per il posto e il CCL applicabile, con le clausole che proteggono l'azienda.",
    intro: "Un contratto di lavoro ben redatto evita la maggior parte delle controversie: orario, ore supplementari, vacanze, divieto di concorrenza, riservatezza. Lo redigiamo per il posto interessato.",
    included: [
      "Verifica del contratto collettivo applicabile",
      "Contratto completo adattato al posto",
      "Clausole scritte indispensabili: ore supplementari, divieto di concorrenza, riservatezza",
      "Un giro di correzioni",
    ],
    needs: "Posto, grado d'occupazione, salario, data d'inizio e prassi interne.",
    note: "Alcune clausole valgono solo per scritto, come l'esclusione della compensazione delle ore supplementari (art. 321c CO) o il divieto di concorrenza (art. 340 CO). Un CCL di obbligatorietà generale si applica anche senza adesione.",
    faq: [
      { q: "Un modello per più dipendenti?", a: "Sì, possiamo redigere un modello per più posti simili; indicatelo nella richiesta." },
      { q: "E per un apprendista?", a: "Il contratto di tirocinio segue un modulo ufficiale cantonale; vi orientiamo." },
    ],
  },
  "certificat-de-travail-employeur": {
    name: "Redigere un certificato di lavoro",
    short: "Un certificato veritiero e benevolo, come vuole la legge, senza formule maldestre che vi si potrebbero rimproverare.",
    intro: "Redigere un certificato di lavoro richiede tempo e ha le sue insidie: troppo lusinghiero impegna la vostra responsabilità, troppo severo apre una controversia. Lo redigiamo in base alle vostre indicazioni.",
    included: [
      "Breve questionario sul dipendente",
      "Certificato completo o attestato semplice",
      "Formulazioni conformi alla prassi",
    ],
    needs: "Posto, date, compiti principali e la vostra valutazione di lavoro e condotta.",
    note: "Il certificato deve essere completo, veritiero e benevolo (art. 330a CO). Un certificato falsamente elogiativo può impegnare la vostra responsabilità verso un futuro datore di lavoro.",
    faq: [
      { q: "Certificato intermedio?", a: "Sì, stesso prezzo." },
      { q: "In quanto tempo?", a: "Due giorni lavorativi, o 24 ore con express." },
    ],
  },
  "licenciement-employeur": {
    name: "Licenziare un collaboratore senza errori",
    short: "Verifichiamo il termine di disdetta e i periodi di protezione, poi redigiamo la lettera di licenziamento.",
    intro: "Un licenziamento mal preparato può essere nullo o abusivo. Verifichiamo termini e periodi di protezione, poi redigiamo la lettera di disdetta e la motivazione scritta.",
    included: [
      "Verifica del termine di disdetta e della data di fine",
      "Controllo dei periodi di protezione",
      "Lettera di licenziamento e motivazione scritta",
      "Punti d'attenzione: saldo vacanze, certificato, assicurazioni",
    ],
    needs: "Il contratto, la situazione del dipendente (assenze, gravidanza…) e il motivo.",
    note: "Una disdetta data durante un periodo di protezione (malattia, infortunio, gravidanza, servizio) è nulla (art. 336c CO). Un licenziamento abusivo può costare fino a sei mesi di salario (art. 336a CO).",
    faq: [
      { q: "E un licenziamento immediato?", a: "Richiede cause gravi (art. 337 CO), spesso precedute da un ammonimento. Valutiamo prima il rischio." },
      { q: "Serve un colloquio preliminare?", a: "In generale non è obbligatorio, ma è consigliato. Vi diamo una traccia." },
    ],
  },
  "avertissement-employe": {
    name: "Ammonimento scritto",
    short: "Descriviamo i fatti, le vostre aspettative e le possibili conseguenze, perché l'ammonimento regga in caso di lite.",
    intro: "Ritardi ripetuti, comportamento inadeguato, istruzioni ignorate: un ammonimento scritto, preciso e proporzionato protegge l'impresa se la situazione porta a un licenziamento.",
    included: [
      "Descrizione fattuale delle mancanze",
      "Aspettative chiare e conseguenze annunciate",
      "Ammonimento pronto da consegnare",
    ],
    needs: "I fatti, le date ed eventuali ammonimenti precedenti.",
    note: "Per una mancanza di gravità media, un licenziamento immediato presuppone di regola un ammonimento precedente rimasto senza effetto.",
    faq: [
      { q: "Il dipendente deve firmare?", a: "Una firma per ricevuta è utile; altrimenti consegnatelo davanti a un testimone." },
      { q: "Per quanto tempo resta valido?", a: "Non c'è una durata fissa; più è vecchio, meno pesa." },
    ],
  },
  "reglement-du-personnel": {
    name: "Regolamento del personale",
    short: "Le regole della casa, scritte una volta per tutto il team, dagli orari alle spese fino al telelavoro.",
    intro: "Già con pochi dipendenti, un regolamento del personale evita di rinegoziare ogni regola. Lo redigiamo per la vostra impresa, coerente con contratti e CCL.",
    included: [
      "Questionario sulle vostre prassi",
      "Regolamento completo: orario, assenze, spese, telelavoro, informatica, dati",
      "Consigli di introduzione e comunicazione",
      "Un giro di correzioni",
    ],
    needs: "I contratti tipo, le prassi attuali e il CCL applicabile.",
    note: "Il regolamento deve essere portato a conoscenza dei dipendenti e integrato nei contratti per essere opponibile.",
    faq: [
      { q: "Da quanti dipendenti?", a: "Già da due o tre fa risparmiare tempo ed evita disparità di trattamento." },
      { q: "Si può modificare in seguito?", a: "Sì, rispettando i termini per la modifica delle condizioni di lavoro." },
    ],
  },
  "pack-conformite-nlpd": {
    name: "Conformità alla nLPD",
    short: "Informativa sulla privacy, registro delle attività di trattamento e clausole aggiornate, per rispettare la legge sulla protezione dei dati.",
    intro: "Dal 1° settembre 2023 la nuova legge sulla protezione dei dati si applica a tutte le imprese. Facciamo l'inventario dei vostri trattamenti e redigiamo i documenti essenziali.",
    included: [
      "Inventario guidato dei trattamenti e dei responsabili del trattamento",
      "Informativa sulla protezione dei dati per sito e clienti",
      "Registro delle attività di trattamento",
      "Clausole per contratti e responsabili del trattamento",
    ],
    needs: "Il sito, gli strumenti (CRM, newsletter, contabilità, cloud) e i tipi di dati.",
    note: "Dovete informare le persone della raccolta dei loro dati (art. 19 LPD). Le violazioni intenzionali di certi obblighi espongono i responsabili a multe fino a CHF 250'000 (art. 60 LPD).",
    faq: [
      { q: "Il registro è obbligatorio per una PMI?", a: "Non sempre sotto i 250 dipendenti, ma resta la miglior prova di conformità ed è spesso richiesto dai clienti." },
      { q: "E il GDPR?", a: "Se si applica a voi, lo integriamo nei documenti." },
    ],
  },
  "politique-de-confidentialite": {
    name: "Informativa sulla privacy del vostro sito",
    short: "Scritta in base agli strumenti che usate davvero (moduli, statistiche, newsletter), conforme alla nLPD.",
    intro: "Il vostro sito raccoglie dati tramite un modulo, statistiche o una newsletter? Gli serve un'informativa esatta, adattata agli strumenti che usate davvero.",
    included: [
      "Inventario degli strumenti del sito",
      "Informativa completa",
      "Note legali del sito",
    ],
    needs: "L'indirizzo del sito e l'elenco degli strumenti (hosting, analytics, moduli, newsletter).",
    note: "Un'informativa generica che non corrisponde ai trattamenti reali non adempie l'obbligo d'informare (art. 19 LPD).",
    faq: [
      { q: "E i cookie?", a: "Vi indichiamo se serve un banner secondo i vostri strumenti." },
      { q: "In più lingue?", a: "Traduzione possibile, prezzo confermato prima di iniziare." },
    ],
  },
  "relecture-bail-commercial": {
    name: "Verificare un contratto di locazione commerciale",
    short: "Prima della firma vi mostriamo cosa negoziare, come l'indicizzazione, la durata o il ripristino all'uscita.",
    intro: "Una locazione commerciale vi impegna spesso per cinque anni o più. La rileggiamo e vi segnaliamo le clausole sfavorevoli e i punti da negoziare.",
    included: [
      "Rilettura completa del contratto e degli allegati",
      "Punti da negoziare: pigione, indicizzazione, durata, opzioni, lavori, ripristino",
      "Elenco di domande da porre al locatore",
    ],
    needs: "Il progetto di contratto, gli allegati ed eventualmente il verbale di consegna.",
    note: "Anche la pigione iniziale di un locale commerciale può essere contestata entro 30 giorni (art. 270 CO). Il limite di tre mesi di garanzia vale solo per le abitazioni.",
    faq: [
      { q: "E se ho già firmato?", a: "La verifica vi indica i vostri diritti e i termini da sorvegliare." },
      { q: "Rilevamento di un'attività?", a: "Indicatelo: subentro nel contratto e buonuscita vengono analizzati." },
    ],
  },
  "convention-d-actionnaires": {
    name: "Patto parasociale o accordo tra soci",
    short: "Fissare le regole tra soci finché tutto va bene, in particolare decisioni, uscita e riacquisto delle quote.",
    intro: "Gli statuti non regolano tutto. Un patto parasociale organizza le decisioni, l'entrata e l'uscita di un socio e protegge ciascuno in caso di disaccordo.",
    included: [
      "Colloquio preliminare",
      "Patto completo: governance, trasferimenti, prelazione, uscita, divieto di concorrenza",
      "Pene convenzionali e meccanismi di stallo",
      "Un giro di correzioni",
    ],
    needs: "Gli statuti, la ripartizione del capitale e i punti sensibili tra soci.",
    note: "Il patto vincola i soci tra loro, non la società: le pene convenzionali ne assicurano il rispetto.",
    faq: [
      { q: "Più di tre soci?", a: "Il prezzo è confermato prima di iniziare." },
      { q: "Serve un notaio?", a: "Non per il patto; la modifica degli statuti di una SA o Sagl richiede un atto pubblico." },
    ],
  },
  "statuts-d-association": {
    name: "Statuti di associazione",
    short: "Statuti conformi al Codice civile e adatti alla vostra associazione, dallo scopo alla gestione delle finanze.",
    intro: "Club sportivo, associazione culturale, progetto di quartiere: redigiamo statuti chiari, conformi al Codice civile, e il verbale dell'assemblea costitutiva.",
    included: [
      "Statuti completi",
      "Verbale dell'assemblea costitutiva",
      "Indicazioni per l'iscrizione al registro di commercio se necessaria",
    ],
    needs: "Lo scopo dell'associazione, i membri fondatori e l'organizzazione desiderata.",
    note: "Gli statuti devono essere scritti e indicare scopo, mezzi e organizzazione dell'associazione (art. 60 CC).",
    faq: [
      { q: "L'iscrizione al registro di commercio è obbligatoria?", a: "Solo in certi casi (attività commerciale, revisione obbligatoria). Ve lo precisiamo." },
      { q: "Si possono modificare gli statuti?", a: "Sì, con decisione dell'assemblea generale." },
    ],
  },
};

export const SERVICE_TEXT_IT = { services, categories };
